import { buildCatalogCategoryTree, type DomainCategoryRecord } from './catalog-category-tree'
import type { PortalData, CatalogItem } from './nocobase-portal-data'
import type { SecurityGovernancePolicyRecord } from './nocobase-security-governance'

const env = (import.meta as { env?: Record<string, string | boolean | undefined> }).env ?? {}

export function isDemoFallbackEnabled() {
  const value = String(env.VITE_PORTAL_DEMO_FALLBACK_ENABLED ?? '').trim().toLowerCase()
  return value === '1' || value === 'true' || value === 'on' || value === 'yes'
}

const categoryRecords: DomainCategoryRecord[] = [
  { id: 'grid-production', name: '生产运行数据', parentId: null },
  { id: 'grid-metering', name: '量测采集数据', parentId: 'grid-production' },
  { id: 'grid-customer-measure', name: '用户侧量测', parentId: 'grid-metering' },
  { id: 'grid-energy', name: '电量数据', parentId: 'grid-metering' },
  { id: 'grid-event', name: '事件类数据', parentId: 'grid-metering' },
  { id: 'grid-unlinked', name: '未关联归档', parentId: 'grid-metering' },
  { id: 'grid-marketing', name: '营销服务数据', parentId: null },
]

const informationCategoryRecords: DomainCategoryRecord[] = [
  { id: 'info-operation', name: '电网运行量测', parentId: null },
  { id: 'info-customer', name: '用户侧明细', parentId: null },
]

const sourceRecords: DomainCategoryRecord[] = [
  { id: 'dept-dispatch', name: '调控中心', parentId: null },
  { id: 'dept-metering', name: '计量中心', parentId: null },
  { id: 'dept-distribution', name: '配电自动化中心', parentId: null },
]

function createPhysicalTables(tableName: string, sourceSystem: string) {
  return {
    baseline: tableName,
    businessTimeField: 'DATA_TIME',
    tables: [tableName],
    sourceSystems: [sourceSystem],
    rows: [
      {
        tableName,
        sourceSystem,
        businessTimeField: 'DATA_TIME',
        isBaseline: true,
      },
    ],
  }
}

function createCatalogItem(overrides: Partial<CatalogItem> & Pick<CatalogItem, 'id' | 'code' | 'name'>): CatalogItem {
  const { id, code, name, ...restOverrides } = overrides
  const categoryId = overrides.categoryId ?? 'grid-metering'
  const informationCategoryId = overrides.informationCategoryId ?? 'info-operation'
  const departmentId = overrides.departmentId ?? 'dept-metering'
  const sourceSystem = overrides.sourceSystem ?? '用电信息采集 2.0'
  const sourceTable = overrides.sourceTable ?? 'DWD_METER_CURVE_15M'
  const fieldRows = overrides.fieldRows ?? [
    {
      fieldName: '采集时间',
      englishName: 'DATA_TIME',
      fieldType: 'DATETIME',
      length: '19',
      nullable: '否',
      shared: '否',
      primary: '是',
      description: '量测曲线采集时间',
    },
    {
      fieldName: '户号',
      englishName: 'CONS_NO',
      fieldType: 'VARCHAR',
      length: '32',
      nullable: '否',
      shared: '否',
      primary: '否',
      description: '用户侧业务标识，默认按敏感字段管控',
    },
    {
      fieldName: '有功功率',
      englishName: 'P_ACTIVE',
      fieldType: 'DECIMAL',
      length: '18,4',
      nullable: '是',
      shared: '是',
      primary: '否',
      description: '十五分钟有功功率量测值',
    },
  ]

  return {
    id,
    code,
    name,
    categoryId,
    category: overrides.category ?? '量测采集数据',
    categoryAncestorIds: overrides.categoryAncestorIds ?? ['grid-production', categoryId],
    businessAttributeId: '',
    businessAttribute: '生产运行',
    businessAttributePath: '生产运行',
    businessAttributeAncestorIds: [],
    industryCategory: '电网',
    businessCategoryId: categoryId,
    businessCategory: overrides.businessCategory ?? '量测采集数据',
    businessCategoryPath: overrides.businessCategoryPath ?? '生产运行数据 / 量测采集数据',
    informationCategoryId,
    informationCategoryAncestorIds: [informationCategoryId],
    informationCategory: overrides.informationCategory ?? '电网运行量测',
    informationCategoryPath: overrides.informationCategoryPath ?? '电网运行量测',
    openTypeId: '',
    openType: '受控共享',
    serviceTypeId: '',
    serviceType: '数据表',
    supplyMethod: '接口',
    sharingAttribute: '条件共享',
    departmentId,
    department: overrides.department ?? '计量中心',
    departmentAncestorIds: [departmentId],
    regionId: '',
    regionAncestorIds: [],
    contact: 'security-ops@example.com',
    tags: ['量测数据', '安全管控', '分类分级'],
    description: overrides.description ?? '用于演示电网量测数据分类分级、字段安全策略、血缘关系和访问控制策略联动。',
    summary: overrides.summary ?? '十五分钟量测曲线资源，包含用户侧标识和功率曲线字段。',
    updateCycleId: '',
    updateCycle: '15分钟',
    format: ['TABLE', 'API'],
    timeScope: '2026年至今',
    publishDate: '2026-06-01',
    updateTime: '2026-06-22 14:00:00',
    areaScope: '省公司',
    count: '1,280,000',
    countValue: 1280000,
    fieldCount: fieldRows.length,
    usageCount: 42,
    apiCount: 3,
    fieldRows,
    dataLineage: {
      nodes: [
        {
          id: 'source-metering',
          name: sourceSystem,
          nodeType: 'data_source',
          resourceCode: '',
          layer: '采集源',
          ownerId: departmentId,
          ownerName: overrides.department ?? '计量中心',
          tableCount: 1,
          tables: [{ tableName: sourceTable, description: '源端采集表', rawLayer: 'source' }],
        },
        {
          id: overrides.id,
          name: overrides.name,
          nodeType: 'warehouse_resource',
          resourceCode: overrides.code,
          layer: 'DWD',
          ownerId: departmentId,
          ownerName: overrides.department ?? '计量中心',
          tableCount: 1,
          tables: [{ tableName: sourceTable, description: '安全管控基准表', rawLayer: 'DWD' }],
        },
        {
          id: 'api-secure-share',
          name: '受控共享 API',
          nodeType: 'data_api',
          resourceCode: 'API-SECURE-SHARE',
          layer: '服务层',
          ownerId: 'dept-dispatch',
          ownerName: '调控中心',
          tableCount: 0,
          tables: [],
        },
      ],
      edges: [
        { fromId: 'source-metering', fromName: sourceSystem, toId: overrides.id, toName: overrides.name },
        { fromId: overrides.id, fromName: overrides.name, toId: 'api-secure-share', toName: '受控共享 API' },
      ],
      upstream: [],
      downstream: [],
      excludedNodeIds: [],
      excludedEdgeKeys: [],
    },
    sourceSystem,
    sourceTable,
    physicalTables: createPhysicalTables(sourceTable, sourceSystem),
    mapPreview: null,
    linkInfo: { primary: '', items: [] },
    remarks: '',
    searchText: [
      name,
      code,
      '量测数据 分类分级 字段安全 访问控制 跨域共享',
      sourceSystem,
      sourceTable,
      ...fieldRows.flatMap((field) => [field.fieldName, field.englishName]),
    ].join(' '),
    ...restOverrides,
  }
}

const demoCatalogItems = [
  createCatalogItem({
    id: 'grid-meter-curve-15m',
    code: 'GRID-METER-SEC-001',
    name: '用户侧十五分钟负荷曲线',
  }),
  createCatalogItem({
    id: 'grid-dispatch-realtime',
    code: 'GRID-DISPATCH-SEC-002',
    name: '调度实时运行量测',
    categoryId: 'grid-production',
    category: '生产运行数据',
    categoryAncestorIds: ['grid-production'],
    businessCategory: '生产运行数据',
    businessCategoryPath: '生产运行数据',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-dispatch',
    department: '调控中心',
    sourceSystem: '调控云',
    sourceTable: 'DWD_DISPATCH_REALTIME_MEASURE',
    summary: '实时调度量测资源，默认按核心运行数据进行安全管控。',
  }),
  createCatalogItem({
    id: 'grid-lvf-volt-001',
    code: 'GRID-LVF-VOLT-001',
    name: '低频电压曲线',
    categoryId: 'grid-metering',
    category: '量测采集数据',
    categoryAncestorIds: ['grid-production', 'grid-metering'],
    businessCategoryPath: '生产运行数据 / 量测采集数据',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-dispatch',
    department: '调控中心',
    sourceSystem: '调度自动化',
    sourceTable: '低频电压曲线表',
    summary: '主网测点 5 分钟低频电压曲线，按设备档案与位置编码组织，明细受控。',
    description: '演示低频电压曲线资源的分类分级、字段安全策略与访问控制联动。',
    tags: ['量测数据', '安全管控', '分类分级', '主网量测'],
    updateCycle: '15分钟',
    fieldRows: [
      { fieldName: '采集时间', englishName: 'DATA_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '量测曲线采集时间' },
      { fieldName: '设备档案标识', englishName: 'PSR_ID', fieldType: 'VARCHAR', length: '64', nullable: '否', shared: '否', primary: '否', description: '设备档案关联标识，按敏感字段管控' },
      { fieldName: '设备类型', englishName: 'EQUIP_TYPE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '主变、母线、线路等设备类型' },
      { fieldName: '位置编码', englishName: 'POS_CODE', fieldType: 'VARCHAR', length: '10', nullable: '否', shared: '否', primary: '否', description: '101 高压侧、102 中压侧、103 低压侧、107 起点、108 终点' },
      { fieldName: '量测项', englishName: 'MEASURE_TYPE', fieldType: 'VARCHAR', length: '30', nullable: '否', shared: '是', primary: '否', description: 'A/B/C 相电压、线电压等量测项' },
      { fieldName: '电压', englishName: 'VOLTAGE', fieldType: 'DECIMAL', length: '12,4', nullable: '否', shared: '是', primary: '否', description: '电压量测值（kV）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'grid-lvf-curr-002',
    code: 'GRID-LVF-CURR-002',
    name: '低频电流曲线',
    categoryId: 'grid-metering',
    category: '量测采集数据',
    categoryAncestorIds: ['grid-production', 'grid-metering'],
    businessCategoryPath: '生产运行数据 / 量测采集数据',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-dispatch',
    department: '调控中心',
    sourceSystem: '调度自动化',
    sourceTable: '低频电流曲线表',
    summary: '主网测点 5 分钟低频电流曲线，按设备档案与位置编码组织，明细受控。',
    tags: ['量测数据', '安全管控', '分类分级', '主网量测'],
    updateCycle: '15分钟',
    fieldRows: [
      { fieldName: '采集时间', englishName: 'DATA_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '量测曲线采集时间' },
      { fieldName: '设备档案标识', englishName: 'PSR_ID', fieldType: 'VARCHAR', length: '64', nullable: '否', shared: '否', primary: '否', description: '设备档案关联标识，按敏感字段管控' },
      { fieldName: '设备类型', englishName: 'EQUIP_TYPE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '主变、母线、线路等设备类型' },
      { fieldName: '量测项', englishName: 'MEASURE_TYPE', fieldType: 'VARCHAR', length: '30', nullable: '否', shared: '是', primary: '否', description: 'A/B/C 相电流等量测项' },
      { fieldName: '电流', englishName: 'CURRENT', fieldType: 'DECIMAL', length: '12,4', nullable: '否', shared: '是', primary: '否', description: '电流量测值（A）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'cust-daily-energy-003',
    code: 'CUST-DAILY-ENERGY-003',
    name: '日冻结电能示值',
    categoryId: 'grid-energy',
    category: '电量数据',
    categoryAncestorIds: ['grid-production', 'grid-metering', 'grid-energy'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 电量数据',
    informationCategoryId: 'info-customer',
    departmentId: 'dept-metering',
    department: '计量中心',
    sourceSystem: '用电信息采集 2.0',
    sourceTable: '日冻结电能示值表',
    summary: '用户每日冻结电能示值（费率分时），按敏感经营数据管控，默认仅密态输出。',
    tags: ['量测数据', '安全管控', '分类分级', '用户电量'],
    updateCycle: '每日',
    fieldRows: [
      { fieldName: '数据日期', englishName: 'DATA_DATE', fieldType: 'DATE', length: '10', nullable: '否', shared: '否', primary: '是', description: '日冻结数据日期' },
      { fieldName: '用户标识', englishName: 'CONS_NO', fieldType: 'VARCHAR', length: '32', nullable: '否', shared: '否', primary: '否', description: '用户侧业务标识，默认按敏感字段管控' },
      { fieldName: '电能表标识', englishName: 'METER_DEV_ID', fieldType: 'VARCHAR', length: '32', nullable: '否', shared: '否', primary: '否', description: '用户侧电能表设备标识' },
      { fieldName: '设备类型', englishName: 'EQUIP_TYPE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '低压用户、中压用户、分布式光伏、充电桩' },
      { fieldName: '正向有功总电能示值', englishName: 'PAP_R', fieldType: 'DECIMAL', length: '20,4', nullable: '否', shared: '是', primary: '否', description: '正向有功总电能示值（kWh）' },
      { fieldName: '正向无功总电能示值', englishName: 'PRP_R', fieldType: 'DECIMAL', length: '20,4', nullable: '否', shared: '是', primary: '否', description: '正向无功总电能示值（kvarh）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'grid-lvf-power-004',
    code: 'GRID-LVF-POWER-004',
    name: '低频功率曲线',
    categoryId: 'grid-metering',
    category: '量测采集数据',
    categoryAncestorIds: ['grid-production', 'grid-metering'],
    businessCategoryPath: '生产运行数据 / 量测采集数据',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-dispatch',
    department: '调控中心',
    sourceSystem: '调度自动化',
    sourceTable: '低频功率曲线表',
    summary: '主网测点 5 分钟低频有功与无功功率曲线，明细受控。',
    tags: ['量测数据', '安全管控', '分类分级', '主网量测'],
    updateCycle: '15分钟',
    fieldRows: [
      { fieldName: '采集时间', englishName: 'DATA_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '量测曲线采集时间' },
      { fieldName: '设备档案标识', englishName: 'PSR_ID', fieldType: 'VARCHAR', length: '64', nullable: '否', shared: '否', primary: '否', description: '设备档案关联标识，按敏感字段管控' },
      { fieldName: '设备类型', englishName: 'EQUIP_TYPE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '主变、母线、线路等设备类型' },
      { fieldName: '有功功率', englishName: 'P_ACTIVE', fieldType: 'DECIMAL', length: '16,4', nullable: '否', shared: '是', primary: '否', description: '有功功率量测值（MW）' },
      { fieldName: '无功功率', englishName: 'P_REACTIVE', fieldType: 'DECIMAL', length: '16,4', nullable: '否', shared: '是', primary: '否', description: '无功功率量测值（Mvar）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'cust-power-curve-005',
    code: 'CUST-POWER-CURVE-005',
    name: '电能示值曲线',
    categoryId: 'grid-customer-measure',
    category: '用户侧量测',
    categoryAncestorIds: ['grid-production', 'grid-metering', 'grid-customer-measure'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 用户侧量测',
    informationCategoryId: 'info-customer',
    departmentId: 'dept-metering',
    department: '计量中心',
    sourceSystem: '用电信息采集 2.0',
    sourceTable: '电能示值曲线表',
    summary: '用户 A/B/C 相电压电流与功率量测曲线，按敏感数据管控，默认仅密态输出。',
    tags: ['量测数据', '安全管控', '分类分级', '用户负荷'],
    updateCycle: '15分钟',
    fieldRows: [
      { fieldName: '采集时间', englishName: 'DATA_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '用户量测采集时间' },
      { fieldName: '用户标识', englishName: 'CONS_NO', fieldType: 'VARCHAR', length: '32', nullable: '否', shared: '否', primary: '否', description: '用户侧业务标识，默认按敏感字段管控' },
      { fieldName: '量测项', englishName: 'MEASURE_TYPE', fieldType: 'VARCHAR', length: '30', nullable: '否', shared: '是', primary: '否', description: 'A/B/C 相电压电流、有功、无功、功率因数' },
      { fieldName: '量测值', englishName: 'VALUE', fieldType: 'DECIMAL', length: '18,6', nullable: '否', shared: '是', primary: '否', description: '按量测项区分的量测值（电压 kV、电流 A、功率 kW）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'grid-lvf-pf-006',
    code: 'GRID-LVF-PF-006',
    name: '低频功率因数曲线',
    categoryId: 'grid-metering',
    category: '量测采集数据',
    categoryAncestorIds: ['grid-production', 'grid-metering'],
    businessCategoryPath: '生产运行数据 / 量测采集数据',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-dispatch',
    department: '调控中心',
    sourceSystem: '调度自动化',
    sourceTable: '低频功率因数曲线表',
    summary: '线路测点 5 分钟低频功率因数曲线，仅提供聚合共享。',
    tags: ['量测数据', '安全管控', '分类分级', '电能质量'],
    updateCycle: '15分钟',
    fieldRows: [
      { fieldName: '采集时间', englishName: 'DATA_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '量测曲线采集时间' },
      { fieldName: '设备档案标识', englishName: 'PSR_ID', fieldType: 'VARCHAR', length: '64', nullable: '否', shared: '否', primary: '否', description: '设备档案关联标识，按敏感字段管控' },
      { fieldName: '功率因数', englishName: 'POWER_FACTOR', fieldType: 'DECIMAL', length: '8,4', nullable: '否', shared: '是', primary: '否', description: '功率因数量测值（0~1）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'cust-outage-event-007',
    code: 'CUST-OUTAGE-EVENT-007',
    name: '用户停复电事件',
    categoryId: 'grid-event',
    category: '事件类数据',
    categoryAncestorIds: ['grid-production', 'grid-metering', 'grid-event'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 事件类数据',
    informationCategoryId: 'info-customer',
    departmentId: 'dept-metering',
    department: '计量中心',
    sourceSystem: '用电信息采集 2.0',
    sourceTable: '用户停复电事件表',
    summary: '用户停电与复电事件明细，按敏感数据管控，默认仅密态或聚合输出。',
    tags: ['量测数据', '安全管控', '分类分级', '停复电'],
    updateCycle: '实时',
    fieldRows: [
      { fieldName: '事件时间', englishName: 'EVENT_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '停电或复电发生时间' },
      { fieldName: '用户标识', englishName: 'CONS_NO', fieldType: 'VARCHAR', length: '32', nullable: '否', shared: '否', primary: '否', description: '用户侧业务标识，默认按敏感字段管控' },
      { fieldName: '事件类型', englishName: 'EVENT_TYPE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '停电或复电' },
      { fieldName: '事件来源', englishName: 'EVENT_SOURCE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '事件来源通道' },
      { fieldName: '停电时长', englishName: 'OUTAGE_DURATION_MIN', fieldType: 'DECIMAL', length: '12,2', nullable: '是', shared: '是', primary: '否', description: '停电持续分钟数' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'grid-switch-event-008',
    code: 'GRID-SWITCH-EVENT-008',
    name: '开关变位事件',
    categoryId: 'grid-event',
    category: '事件类数据',
    categoryAncestorIds: ['grid-production', 'grid-metering', 'grid-event'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 事件类数据',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-distribution',
    department: '配电自动化中心',
    sourceSystem: '配电自动化',
    sourceTable: '开关变位事件表',
    summary: '配网开关变位、故障跳闸与事故总事件，按重要运行数据管控。',
    tags: ['量测数据', '安全管控', '分类分级', '开关事件'],
    updateCycle: '实时',
    fieldRows: [
      { fieldName: '事件时间', englishName: 'EVENT_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '开关变位发生时间' },
      { fieldName: '设备档案标识', englishName: 'PSR_ID', fieldType: 'VARCHAR', length: '64', nullable: '否', shared: '否', primary: '否', description: '设备档案关联标识，按敏感字段管控' },
      { fieldName: '设备类型', englishName: 'EQUIP_TYPE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '断路器、负荷开关、柱上开关' },
      { fieldName: '事件类型', englishName: 'EVENT_TYPE', fieldType: 'VARCHAR', length: '30', nullable: '否', shared: '是', primary: '否', description: '开关变位、故障跳闸、事故总' },
      { fieldName: '开关状态', englishName: 'SWITCH_STATE', fieldType: 'SMALLINT', length: '2', nullable: '否', shared: '是', primary: '否', description: '0 分、1 合' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'grid-no-relad-009',
    code: 'GRID-NO-RELAD-009',
    name: '未关联量测归档',
    categoryId: 'grid-unlinked',
    category: '未关联归档',
    categoryAncestorIds: ['grid-production', 'grid-metering', 'grid-unlinked'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 未关联归档',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-metering',
    department: '计量中心',
    sourceSystem: '历史量测中心',
    sourceTable: '未关联量测归档表',
    summary: '未与设备档案关联的量测归档，仅允许聚合或密态输出，禁止明细直取。',
    tags: ['量测数据', '安全管控', '分类分级', '未关联'],
    updateCycle: '15分钟',
    fieldRows: [
      { fieldName: '采集时间', englishName: 'DATA_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '未关联量测采集时间' },
      { fieldName: '来源通道', englishName: 'SOURCE_TAG', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '主网遥测、配网遥测、用户量测' },
      { fieldName: '量测项', englishName: 'MEASURE_TYPE', fieldType: 'VARCHAR', length: '30', nullable: '否', shared: '是', primary: '否', description: '电压、电流、有功、无功' },
      { fieldName: '量测值', englishName: 'VALUE', fieldType: 'DECIMAL', length: '18,6', nullable: '否', shared: '是', primary: '否', description: '未关联量测值' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'grid-tmr-energy-010',
    code: 'GRID-TMR-ENERGY-010',
    name: '主网电能示值',
    categoryId: 'grid-energy',
    category: '电量数据',
    categoryAncestorIds: ['grid-production', 'grid-metering', 'grid-energy'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 电量数据',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-metering',
    department: '计量中心',
    sourceSystem: '电能量计量',
    sourceTable: '主网电能示值表',
    summary: '主变、断路器、机组与线路的电能示值，按重要经营数据管控。',
    tags: ['量测数据', '安全管控', '分类分级', '电能示值'],
    updateCycle: '每日',
    fieldRows: [
      { fieldName: '采集时间', englishName: 'DATA_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '电能示值采集时间' },
      { fieldName: '设备档案标识', englishName: 'PSR_ID', fieldType: 'VARCHAR', length: '64', nullable: '否', shared: '否', primary: '否', description: '设备档案关联标识，按敏感字段管控' },
      { fieldName: '设备类型', englishName: 'EQUIP_TYPE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '主变、断路器、机组、线路' },
      { fieldName: '电能类型', englishName: 'ENERGY_TYPE', fieldType: 'VARCHAR', length: '30', nullable: '否', shared: '是', primary: '否', description: '正向有功、反向有功、正向无功、反向无功' },
      { fieldName: '电能示值', englishName: 'READ_VALUE', fieldType: 'DECIMAL', length: '20,4', nullable: '否', shared: '是', primary: '否', description: '电能示值（kWh）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'grid-lvf-phase-011',
    code: 'GRID-LVF-PHASE-011',
    name: '低频日电压相位角曲线',
    categoryId: 'grid-metering',
    category: '采集类数据',
    categoryAncestorIds: ['grid-production', 'grid-metering'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 采集类数据',
    informationCategoryId: 'info-operation',
    departmentId: 'dept-dispatch',
    department: '调控中心',
    sourceSystem: '调控云',
    sourceTable: '低频日电压相位角曲线表',
    summary: '主网测点低频日电压相位角曲线，按电能质量重要运行数据管控，仅提供受控聚合。',
    tags: ['量测数据', '安全管控', '分类分级', '电能质量'],
    updateCycle: '每日',
    fieldRows: [
      { fieldName: '采集时间', englishName: 'DATA_TIME', fieldType: 'DATETIME', length: '23', nullable: '否', shared: '否', primary: '是', description: '量测曲线采集时间' },
      { fieldName: '设备档案标识', englishName: 'PSR_ID', fieldType: 'VARCHAR', length: '64', nullable: '否', shared: '否', primary: '否', description: '设备档案关联标识，按敏感字段管控' },
      { fieldName: '量测项', englishName: 'MEASURE_TYPE', fieldType: 'VARCHAR', length: '30', nullable: '否', shared: '是', primary: '否', description: 'A/B/C 相相位角等量测项' },
      { fieldName: '电压相位角', englishName: 'PHASE_ANGLE', fieldType: 'DECIMAL', length: '10,4', nullable: '否', shared: '是', primary: '否', description: '电压相位角量测值（度）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'cust-hv-daily-info-012',
    code: 'CUST-HV-DAILY-INFO-012',
    name: '高压日用能信息',
    categoryId: 'grid-energy',
    category: '电量数据',
    categoryAncestorIds: ['grid-production', 'grid-metering', 'grid-energy'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 电量数据',
    informationCategoryId: 'info-customer',
    departmentId: 'dept-metering',
    department: '计量中心',
    sourceSystem: '用电信息采集 2.0',
    sourceTable: '高压日用能信息表',
    summary: '高压与专变用户按日冻结的正向分时电能示值，按高敏感经营数据管控。',
    tags: ['量测数据', '安全管控', '分类分级', '用户电量'],
    updateCycle: '每日',
    fieldRows: [
      { fieldName: '数据日期', englishName: 'DATA_DATE', fieldType: 'DATE', length: '10', nullable: '否', shared: '否', primary: '是', description: '高压用户日用能数据日期' },
      { fieldName: '用户标识', englishName: 'CONS_NO', fieldType: 'VARCHAR', length: '32', nullable: '否', shared: '否', primary: '否', description: '高压用户业务标识，按敏感字段管控' },
      { fieldName: '设备类型', englishName: 'EQUIP_TYPE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '高压用户、专变用户' },
      { fieldName: '正向有功总电能示值', englishName: 'PAP_R', fieldType: 'BIGINT', length: '20', nullable: '否', shared: '是', primary: '否', description: '高压用户正向有功总电能示值（kWh）' },
      { fieldName: '正向无功总电能示值', englishName: 'PRP_R', fieldType: 'BIGINT', length: '20', nullable: '否', shared: '是', primary: '否', description: '正向无功总电能示值（kvarh）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'cust-lv-daily-info-013',
    code: 'CUST-LV-DAILY-INFO-013',
    name: '低压日用能信息',
    categoryId: 'grid-energy',
    category: '电量数据',
    categoryAncestorIds: ['grid-production', 'grid-metering', 'grid-energy'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 电量数据',
    informationCategoryId: 'info-customer',
    departmentId: 'dept-metering',
    department: '计量中心',
    sourceSystem: '用电信息采集 2.0',
    sourceTable: '低压日用能信息表',
    summary: '低压用户、分布式光伏与充电桩按日冻结的电能示值，按高敏感经营数据管控。',
    tags: ['量测数据', '安全管控', '分类分级', '用户电量'],
    updateCycle: '每日',
    fieldRows: [
      { fieldName: '数据日期', englishName: 'DATA_DATE', fieldType: 'DATE', length: '10', nullable: '否', shared: '否', primary: '是', description: '低压用户日用能数据日期' },
      { fieldName: '用户标识', englishName: 'CONS_NO', fieldType: 'VARCHAR', length: '32', nullable: '否', shared: '否', primary: '否', description: '低压用户业务标识，按敏感字段管控' },
      { fieldName: '设备类型', englishName: 'EQUIP_TYPE', fieldType: 'VARCHAR', length: '50', nullable: '否', shared: '是', primary: '否', description: '低压用户、分布式光伏、充电桩' },
      { fieldName: '正向有功总电能示值', englishName: 'PAP_R', fieldType: 'BIGINT', length: '20', nullable: '否', shared: '是', primary: '否', description: '低压用户正向有功总电能示值（kWh）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
  createCatalogItem({
    id: 'cust-hv-daily-load-014',
    code: 'CUST-HV-DAILY-LOAD-014',
    name: '高压日负荷',
    categoryId: 'grid-metering',
    category: '负荷类数据',
    categoryAncestorIds: ['grid-production', 'grid-metering'],
    businessCategoryPath: '生产运行数据 / 量测采集数据 / 负荷类数据',
    informationCategoryId: 'info-customer',
    departmentId: 'dept-metering',
    department: '计量中心',
    sourceSystem: '用电信息采集 2.0',
    sourceTable: '高压日负荷表',
    summary: '高压用户日最大、最小与平均负荷及日负荷率，按高敏感运行数据管控。',
    tags: ['量测数据', '安全管控', '分类分级', '用户负荷'],
    updateCycle: '每日',
    fieldRows: [
      { fieldName: '数据日期', englishName: 'DATA_DATE', fieldType: 'DATE', length: '10', nullable: '否', shared: '否', primary: '是', description: '高压用户日负荷数据日期' },
      { fieldName: '用户标识', englishName: 'CONS_NO', fieldType: 'VARCHAR', length: '32', nullable: '否', shared: '否', primary: '否', description: '高压用户业务标识，按敏感字段管控' },
      { fieldName: '日最大负荷', englishName: 'MAX_LOAD', fieldType: 'DECIMAL', length: '12,4', nullable: '否', shared: '是', primary: '否', description: '高压用户日最大负荷（kW）' },
      { fieldName: '日最小负荷', englishName: 'MIN_LOAD', fieldType: 'DECIMAL', length: '12,4', nullable: '否', shared: '是', primary: '否', description: '高压用户日最小负荷（kW）' },
      { fieldName: '日平均负荷', englishName: 'AVG_LOAD', fieldType: 'DECIMAL', length: '12,4', nullable: '否', shared: '是', primary: '否', description: '高压用户日平均负荷（kW）' },
      { fieldName: '日负荷率', englishName: 'LOAD_FACTOR', fieldType: 'DECIMAL', length: '8,4', nullable: '否', shared: '是', primary: '否', description: '高压用户日负荷率（0~1）' },
      { fieldName: '质量码', englishName: 'QUALITY_CODE', fieldType: 'VARCHAR', length: '20', nullable: '否', shared: '是', primary: '否', description: '量测质量状态' },
    ],
  }),
]

export function createDemoPortalData(): PortalData {
  const categoryTree = buildCatalogCategoryTree(
    categoryRecords,
    demoCatalogItems.map((item) => ({
      categoryId: item.categoryId,
      categoryAncestorIds: item.categoryAncestorIds,
    })),
  )
  const informationCategoryTree = buildCatalogCategoryTree(
    informationCategoryRecords,
    demoCatalogItems.map((item) => ({
      categoryId: item.informationCategoryId,
      categoryAncestorIds: item.informationCategoryAncestorIds,
    })),
  )
  const sourceTree = buildCatalogCategoryTree(
    sourceRecords,
    demoCatalogItems.map((item) => ({
      categoryId: item.departmentId,
      categoryAncestorIds: item.departmentAncestorIds,
    })),
  )
  const categoryOptions: Array<[string, number]> = [['全部', demoCatalogItems.length]]
  const categoryCounts = new Map<string, number>()
  for (const item of demoCatalogItems) {
    const key = item.category ?? '未分类'
    categoryCounts.set(key, (categoryCounts.get(key) ?? 0) + 1)
  }
  for (const [name, count] of categoryCounts) categoryOptions.push([name, count])
  const departmentOptions: Array<[string, number]> = [['全部', demoCatalogItems.length]]
  const departmentCounts = new Map<string, number>()
  for (const item of demoCatalogItems) {
    departmentCounts.set(item.department, (departmentCounts.get(item.department) ?? 0) + 1)
  }
  for (const [name, count] of departmentCounts) departmentOptions.push([name, count])

  return {
    catalogItems: demoCatalogItems,
    categoryTree,
    businessAttributeTree: [],
    sourceTree,
    regionTree: [],
    informationCategoryTree,
    categoryOptions,
    openOptions: [['全部', demoCatalogItems.length], ['受控共享', demoCatalogItems.length]],
    departmentOptions,
    regionOptions: [['全部', demoCatalogItems.length], ['省公司', demoCatalogItems.length]],
    editOptions: {
      updateCycleOptions: [],
      sharingAttributeOptions: [],
      serviceTypeOptions: [],
      supplyMethodOptions: [],
    },
  }
}

export function createDemoSecurityPolicies(): SecurityGovernancePolicyRecord[] {
  return [
    {
      id: 'sg-grid-meter-curve-15m',
      policyKind: 'resource_profile',
      resourceId: 'grid-meter-curve-15m',
      resourceName: '用户侧十五分钟负荷曲线',
      securityCategoryId: 'personal-sensitive',
      securityCategory: '用户侧敏感数据',
      securityLevelId: 'level-3',
      securityLevel: '3级',
      dataSubjectTypeId: 'customer',
      dataSubjectType: '电力客户',
      securityOwnerUserId: '',
      securityOwnerUserName: '安全管理员',
      securityProfileStatus: 'effective',
      securityReviewStatus: 'reviewed',
      importantDataFlag: true,
      coreControlFlag: true,
      shareScope: 'conditional',
      externalShareAllowed: false,
      openAllowed: false,
      desensitizationRequired: true,
      approvalRequired: true,
      securityOwnerDept: '计量中心',
      assessmentBasis: '含用户侧标识与用电曲线，按中风险敏感量测数据管控。',
      riskNotes: '导出和跨域共享前必须审批并脱敏户号。',
      lastReviewedAt: '2026-06-21T10:00:00+08:00',
      nextReviewAt: '2026-09-21',
      policyCode: 'POL-METER-001',
      policyName: '用户侧量测曲线受控共享策略',
      policySource: '量测数据安全管控组件设计',
      policyStatus: 'effective',
      accessScope: 'internal-controlled',
      approvalMode: 'workflow',
      desensitizationMode: 'tokenize',
      exportAllowed: false,
      exportScope: 'disabled',
      apiAccessAllowed: true,
      apiAuthMode: 'jwt-and-role',
      effectiveFrom: '2026-06-01',
      effectiveTo: '2026-12-31',
      fieldProfilesJson: [],
      fieldPoliciesJson: [],
      securityProfileJson: {},
      policyDetailJson: {},
      securityReviewJson: {},
      fieldSecurityProfileRows: [
        {
          seq: 1,
          fieldCode: 'CONS_NO',
          fieldName: '户号',
          dataType: 'VARCHAR',
          description: '用户侧业务标识',
          informationCategory: '用户侧明细',
          classificationLevel: '敏感经营',
          securityLevel: '3级',
          sensitivityType: '个人/客户标识',
          sensitivityTags: ['客户标识', '准标识符'],
          identifierFlag: true,
          quasiIdentifierFlag: true,
          importantFieldFlag: true,
          levelBasis: '关联用户用电行为',
          riskNotes: '禁止明文导出',
          extra: {},
        },
        {
          seq: 2,
          fieldCode: 'P_ACTIVE',
          fieldName: '有功功率',
          dataType: 'DECIMAL',
          description: '十五分钟有功功率量测值',
          informationCategory: '电网运行量测',
          classificationLevel: '运行明细',
          securityLevel: '3级',
          sensitivityType: '运行敏感',
          sensitivityTags: ['负荷曲线'],
          identifierFlag: false,
          quasiIdentifierFlag: false,
          importantFieldFlag: true,
          levelBasis: '反映用户侧负荷行为',
          riskNotes: '跨域聚合优先走同态加密计算',
          extra: {},
        },
      ],
      fieldSecurityPolicyRows: [
        {
          seq: 1,
          fieldCode: 'CONS_NO',
          fieldName: '户号',
          requiredAccessScope: 'internal-controlled',
          requiredDesensitization: true,
          requiredDesensitizationMode: 'tokenize',
          requiredExportAllowed: false,
          requiredExportScope: 'disabled',
          requiredApiAccessAllowed: true,
          requiredApiReturnMode: 'masked',
          requiredApprovalRequired: true,
          requiredQueryConditionAllowed: false,
          requiredAggregationAllowed: false,
          requiredJoinAllowed: false,
          notes: '仅授权岗位可查看脱敏值',
          extra: {},
        },
      ],
      legacyPhysicalTableRows: [],
      fieldSecurityStats: {
        totalFields: 2,
        sensitiveFieldCount: 2,
        importantFieldCount: 2,
      },
      remarks: '本地演示安全档案',
      createdAt: '2026-06-01T09:00:00+08:00',
      updatedAt: '2026-06-22T14:00:00+08:00',
    },
    {
      id: 'sg-grid-dispatch-realtime',
      policyKind: 'resource_profile',
      resourceId: 'grid-dispatch-realtime',
      resourceName: '调度实时运行量测',
      securityCategoryId: 'core-operation',
      securityCategory: '核心运行数据',
      securityLevelId: 'level-4',
      securityLevel: '4级',
      dataSubjectTypeId: 'grid-device',
      dataSubjectType: '电网设备',
      securityOwnerUserId: '',
      securityOwnerUserName: '调控安全员',
      securityProfileStatus: 'effective',
      securityReviewStatus: 'reviewed',
      importantDataFlag: true,
      coreControlFlag: true,
      shareScope: 'deny-external',
      externalShareAllowed: false,
      openAllowed: false,
      desensitizationRequired: true,
      approvalRequired: true,
      securityOwnerDept: '调控中心',
      assessmentBasis: '涉及实时运行状态，按高风险核心运行数据管控。',
      riskNotes: '原则上不对外共享明细，仅允许授权场景聚合使用。',
      lastReviewedAt: '2026-06-20T16:30:00+08:00',
      nextReviewAt: '2026-08-20',
      policyCode: 'POL-DISPATCH-002',
      policyName: '调度实时量测最小授权策略',
      policySource: '量测数据安全管控组件设计',
      policyStatus: 'effective',
      accessScope: 'production-zone',
      approvalMode: 'dual-approval',
      desensitizationMode: 'aggregate-only',
      exportAllowed: false,
      exportScope: 'disabled',
      apiAccessAllowed: true,
      apiAuthMode: 'mfa-and-role',
      effectiveFrom: '2026-06-01',
      effectiveTo: '2026-12-31',
      fieldProfilesJson: [],
      fieldPoliciesJson: [],
      securityProfileJson: {},
      policyDetailJson: {},
      securityReviewJson: {},
      fieldSecurityProfileRows: [],
      fieldSecurityPolicyRows: [],
      legacyPhysicalTableRows: [],
      fieldSecurityStats: {
        totalFields: 0,
        sensitiveFieldCount: 0,
        importantFieldCount: 0,
      },
      remarks: '本地演示安全档案',
      createdAt: '2026-06-01T09:00:00+08:00',
      updatedAt: '2026-06-22T14:00:00+08:00',
    },
  ]
}
