import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const applicationGovernanceRoutesSource = readFileSync(resolve(process.cwd(), 'src/modules/ApplicationGovernance/routes.tsx'), 'utf8')
const detailPageSource = readFileSync(resolve(process.cwd(), 'src/pages/demand-application-detail-page.tsx'), 'utf8')
const applicationTabSource = readFileSync(resolve(process.cwd(), 'src/components/demand-application-tab-view.tsx'), 'utf8')
const appDataSource = readFileSync(resolve(process.cwd(), 'src/lib/nocobase-app-data.ts'), 'utf8')

test('场景应用详情页已注册独立路由', () => {
  assert.match(applicationGovernanceRoutesSource, /const DemandApplicationDetailPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/demand-application-detail-page'\)\)\.DemandApplicationDetailPage \}\)\)/)
  assert.match(applicationGovernanceRoutesSource, /<Route path="\/demand\/applications\/:id" element={<DemandApplicationDetailPage \/>} \/>/)
  assert.match(detailPageSource, /return withEmbed\(`\/demand\?\$\{searchParams\.toString\(\)\}`\)/)
  assert.match(detailPageSource, /return <Navigate to=\{withEmbed\('\/demand\?tab=application'\)\} replace \/>/)
})

test('场景应用 tab 卡片支持查看详情页与保留下钻交互', () => {
  assert.match(applicationTabSource, /const buildDetailPath = \(id: string\) => appendEmbedToPath\(`\/demand\/applications\/\$\{id\}`/)
  assert.match(applicationTabSource, /if \(item\.hasChildren\) \{\s+onSelectNode\(item\.id\)/s)
  assert.match(applicationTabSource, /navigate\(buildDetailPath\(item\.id\)\)/)
  assert.doesNotMatch(applicationTabSource, /查看下级/)
  assert.match(applicationTabSource, /查看详情/)
  assert.match(applicationTabSource, /to=\{buildDetailPath\(item\.id\)\}/)
})

test('场景应用详情页展示应用信息、下级应用、供需对接与数据资源', () => {
  assert.match(detailPageSource, /useSupplyDemandPortalData\(true, \{ includeRelatedApps: true \}\)/)
  assert.match(detailPageSource, /buildDemandApplicationDetailData\(id \?\? '', appCatalogData\.flatItems, supplyDemandItems, portalData\?\.catalogItems \?\? \[\]\)/)
  assert.match(detailPageSource, /title="场景应用信息"/)
  assert.match(detailPageSource, /title="当前应用关联供需对接与数据资源"/)
  assert.match(detailPageSource, /title="下级应用树形表格"/)
  assert.match(detailPageSource, /const currentTreeSection: DemandApplicationTreeSection = \{/)
  assert.match(detailPageSource, /children: childTreeSections,/)
  assert.match(detailPageSource, /<SubApplicationTreeTable sections=\{\[currentTreeSection\]\} withEmbed=\{withEmbed\} \/>/)
  assert.match(detailPageSource, /sections\.flatMap\(\(section\) => renderRows\(section\)\)/)
  assert.match(detailPageSource, /应用节点/)
  assert.match(detailPageSource, /关联供需对接/)
  assert.match(detailPageSource, /关联数据资源/)
  assert.doesNotMatch(detailPageSource, /section\.app\.tags\.slice\(0, 3\)/)
  assert.doesNotMatch(detailPageSource, /下级 \{section\.children\.length\}/)
  assert.match(detailPageSource, />\s*返回\s*<\/Link>/)
  assert.match(detailPageSource, /<h1 className="text-\[2rem\] font-bold/)
  assert.match(detailPageSource, /flex flex-wrap items-start justify-between gap-4/)
  assert.match(detailPageSource, /<div className="mt-4 flex flex-wrap items-center gap-2 text-\[0\.75rem\] text-\[var\(--text-secondary\)\]">/)
  assert.match(detailPageSource, /const heroStats = \[/)
  assert.match(detailPageSource, /title: '当前供需对接'/)
  assert.match(detailPageSource, /title: '聚合供需总数'/)
  assert.match(detailPageSource, /title: '聚合数据资源'/)
  assert.match(detailPageSource, /title: '下级应用总数'/)
  assert.match(detailPageSource, /lg:grid-cols-\[minmax\(0,60%\)_minmax\(0,40%\)\]/)
  assert.match(detailPageSource, /lg:items-stretch/)
  assert.match(detailPageSource, /flex h-full min-w-0 flex-col lg:pr-2/)
  assert.match(detailPageSource, /mt-auto grid gap-3 pt-6 sm:grid-cols-2 xl:grid-cols-4/)
  assert.match(detailPageSource, /flex h-full flex-col justify-end lg:justify-self-stretch/)
  assert.doesNotMatch(detailPageSource, /返回场景应用目录/)
  assert.match(detailPageSource, /去供需页/)
  assert.match(detailPageSource, /查看资源/)
  assert.match(detailPageSource, /查看详情/)
  assert.doesNotMatch(detailPageSource, /当前场景应用尚未补充详细说明/)
  assert.doesNotMatch(detailPageSource, /title="下级应用清单"/)
  assert.doesNotMatch(detailPageSource, /title=\{`\$\{section\.app\.name\} 关联供需与资源`\}/)
  assert.doesNotMatch(detailPageSource, /当前应用没有下级应用，下面将直接展示本应用关联的供需对接与数据资源。/)
  assert.doesNotMatch(detailPageSource, /title="直接关联供需"/)
  assert.doesNotMatch(detailPageSource, /title="下级应用覆盖"/)
  assert.doesNotMatch(detailPageSource, /直接供需/)
  assert.doesNotMatch(detailPageSource, /下级覆盖/)
  assert.doesNotMatch(detailPageSource, /title="聚合数据资源"/)
  assert.doesNotMatch(detailPageSource, /title="下级应用总数"/)
  assert.doesNotMatch(detailPageSource, /tree-detail-/)
})

test('场景应用详情页使用主题变量兼容暗色模式', () => {
  assert.match(detailPageSource, /bg-\[linear-gradient\(135deg,var\(--surface-hero-start\),var\(--surface-hero-end\)\)\]/)
  assert.match(detailPageSource, /bg-\[linear-gradient\(180deg,var\(--surface-raised-strong\),var\(--surface-muted\)\)\]/)
  assert.match(detailPageSource, /bg-\[var\(--table-header-bg\)\]/)
  assert.match(detailPageSource, /text-\[var\(--text-main\)\]/)
  assert.doesNotMatch(detailPageSource, /bg-white/)
  assert.doesNotMatch(detailPageSource, /text-\[#1a2b3b\]/)
  assert.doesNotMatch(detailPageSource, /text-\[#304255\]/)
  assert.doesNotMatch(detailPageSource, /bg-\[#f8fbfe\]/)
})

test('场景应用详情页为管理员提供编辑场景应用和截图维护能力', () => {
  assert.match(detailPageSource, /import \{ createPortal \} from 'react-dom'/)
  assert.match(detailPageSource, /import \{ canManageCatalogResources \} from '\.\.\/lib\/admin-role'/)
  assert.match(detailPageSource, /updatePortalAppCatalogEntry/)
  assert.match(detailPageSource, /uploadPortalAppCatalogScreenshot/)
  assert.match(detailPageSource, /reload: reloadApplicationCatalog,\s*\} = usePortalAppCatalogData\(true\)/)
  assert.match(detailPageSource, /const canManageApplication = canManageCatalogResources\(session\?\.user\.roles\)/)
  assert.match(detailPageSource, /编辑场景应用/)
  assert.match(detailPageSource, /title="编辑场景应用"/)
  assert.match(detailPageSource, /保存场景应用/)
  assert.match(detailPageSource, /应用截图/)
  assert.match(detailPageSource, /accept="image\/\*"/)
  assert.match(detailPageSource, /const handleApplicationEditScreenshotChange = async \(event: ChangeEvent<HTMLInputElement>\) => \{/)
  assert.match(detailPageSource, /await reloadApplicationCatalog\(\)/)
})

test('场景应用数据层支持 snapscreen 截图上传与关联更新', () => {
  assert.match(appDataSource, /type CreatePortalAppCatalogEntryParams = \{[\s\S]*screenshotAttachmentId\?: string \| null/)
  assert.match(appDataSource, /type UpdatePortalAppCatalogEntryParams = \{/)
  assert.match(appDataSource, /snapscreen\?: unknown/)
  assert.match(appDataSource, /'snapscreen',/)
})
