import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const detailPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-governance-detail-page.tsx'), 'utf8')
const resourceFieldsPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-fields-panel.tsx'), 'utf8')
const resourceApisPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-apis-panel.tsx'), 'utf8')
const resourceAccessSubjectsPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-access-subjects-panel.tsx'), 'utf8')
const resourceAccessSubjectsSource = readFileSync(resolve(process.cwd(), 'src/lib/resource-access-subjects.ts'), 'utf8')
const resourcePhysicalTablePanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-physical-table-panel.tsx'), 'utf8')
const resourceIngestValidationDialogSource = readFileSync(resolve(process.cwd(), 'src/components/resource-ingest-validation-dialog.tsx'), 'utf8')
const resourceIngestValidationSource = readFileSync(resolve(process.cwd(), 'src/lib/resource-ingest-validation.ts'), 'utf8')
const resourceEditDialogSource = readFileSync(resolve(process.cwd(), 'src/components/resource-edit-dialog.tsx'), 'utf8')
const resourceEditSource = readFileSync(resolve(process.cwd(), 'src/lib/nocobase-resource-edit.ts'), 'utf8')
const runtimeClientSource = readFileSync(resolve(process.cwd(), 'src/lib/security-runtime-client.ts'), 'utf8')
const accessPoliciesPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-access-policies-panel.tsx'), 'utf8')
const homomorphicPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-homomorphic-panel.tsx'), 'utf8')
const collectionPageSource = readFileSync(resolve(process.cwd(), 'src/components/security-v3-collection-page.tsx'), 'utf8')
const moduleTabsSource = readFileSync(resolve(process.cwd(), 'src/components/security-module-tabs.tsx'), 'utf8')
const relationSource = readFileSync(resolve(process.cwd(), 'src/lib/resource-security-relations.ts'), 'utf8')
const securityV3PagesSource = readFileSync(resolve(process.cwd(), 'src/pages/security-v3-pages.tsx'), 'utf8')

test('安全管控详情页支持返回原列表并兜底跳回数据资源列表', () => {
  assert.match(detailPageSource, /type SecurityGovernanceDetailLocationState = \{/)
  assert.match(detailPageSource, /const returnTo = typeof locationState\?\.returnTo === 'string'/)
  assert.match(detailPageSource, /const handleGoBack = \(\) => \{/)
  assert.match(detailPageSource, /if \(returnTo\) \{/)
  assert.match(detailPageSource, /navigate\(returnTo\)/)
  assert.match(detailPageSource, /navigate\(-1\)/)
  assert.match(detailPageSource, /navigate\(withEmbed\('\/security-governance\/resources\/catalog'\)\)/)
  assert.match(detailPageSource, /返回数据资源/)
})

test('安全管控详情页按资源 ID 查询并提供资源目录详情与编辑入口', () => {
  assert.match(detailPageSource, /catalogItems\.find\(\(entry\) => entry\.id === id\)/)
  assert.match(detailPageSource, /to=\{withEmbed\(`\/catalog\/\$\{item\.id\}`\)\}/)
  assert.match(detailPageSource, /资源目录详情/)
  assert.match(detailPageSource, /ResourceFieldsPanel/)
  assert.doesNotMatch(detailPageSource, /SecurityGovernanceProfileEditDialog/)
  assert.doesNotMatch(detailPageSource, /SecurityGovernanceFieldEditDialog/)
  assert.match(detailPageSource, /编辑数据资源/)
  assert.match(detailPageSource, /<ResourceEditDialog/)
  assert.match(detailPageSource, /mode="edit"/)
  assert.match(detailPageSource, /resourceId=\{item\.id\}/)
  assert.match(detailPageSource, /securityGovernanceMode/)
  assert.match(detailPageSource, /await refresh\(\)/)
  assert.match(detailPageSource, /ensureDefaultSecurityApi\(item\.id\)/)
  assert.doesNotMatch(detailPageSource, /<DataItemsEditDialog/)
})

test('详情页接入规则 tab 聚合数据源规则、校验规则、抽样结果和执行日志', () => {
  assert.match(detailPageSource, /\['physicalTable', '接入规则'\]/)
  assert.match(detailPageSource, /activeTab === 'physicalTable'/)
  assert.match(detailPageSource, /<ResourceIngestSamplesPanel/)
  assert.match(detailPageSource, /useResourceIngestSamples\(item\?\.id, statEnabled\)/)
  assert.match(detailPageSource, /formatNumber\(ingestSamples\.sampleCount\)/)
  assert.match(resourcePhysicalTablePanelSource, /以最新 \{data\?\.limit \?\? 10\} 条记录为校验窗口/)
  assert.match(resourcePhysicalTablePanelSource, /data\.samplingEnabled \? `\$\{data\.samplingRate\}%` : '未启用'/)
  assert.match(resourcePhysicalTablePanelSource, /data\.validationRule\.requiredFields/)
  assert.match(resourcePhysicalTablePanelSource, /data\.validationRule\.numericRanges/)
  assert.match(resourcePhysicalTablePanelSource, /data\.validationRule\.duplicateKeys/)
  assert.match(resourcePhysicalTablePanelSource, /data\.validationResults\[rowIndex\]\?\.passed/)
  assert.match(resourcePhysicalTablePanelSource, /校验结果/)
  assert.match(resourcePhysicalTablePanelSource, /刷新抽样/)
  assert.match(resourcePhysicalTablePanelSource, /按 \{data\.samplingRate\}% 抽中 \{data\.sampleCount\} 条/)
  assert.match(detailPageSource, /关联数据源与安全接入规则/)
  assert.match(detailPageSource, /字段校验规则/)
  assert.match(detailPageSource, /规则抽样与逐条校验/)
  assert.match(detailPageSource, /最近接入规则执行日志/)
  assert.doesNotMatch(detailPageSource, /<PhysicalTablesEditDialog/)
  assert.doesNotMatch(detailPageSource, /<LatestDataPreviewPanel/)
})

test('资源字段随当前数据资源维护且不再作为独立二级导航', () => {
  assert.match(resourceFieldsPanelSource, /collection: 'eco_resource_security_fields'/)
  assert.match(resourceFieldsPanelSource, /filter: \{ resource_id: resourceId \}/)
  assert.match(resourceFieldsPanelSource, /transformSaveValues: \(values\) => \(\{ \.\.\.values, resource_id: resourceId \}\)/)
  assert.match(resourceFieldsPanelSource, /onRecordsChange: \(records\) => onFieldsChange\?\.\(records\)/)
  assert.match(resourceFieldsPanelSource, /<SecurityV3CollectionPage config=\{config\} embedded \/>/)
  assert.match(collectionPageSource, /config\.onRecordsChange\?\.\(nextRows\)/)
  assert.match(collectionPageSource, /Boolean\(value \?\? field\.defaultValue \?\? false\)/)
  assert.doesNotMatch(moduleTabsSource, /\/security-governance\/resources\/fields/)
})

test('顶部字段数量使用当前资源字段集合的实时记录数', () => {
  assert.match(relationSource, /listSecurityV3Records\('eco_resource_security_fields'/)
  assert.match(relationSource, /filter: \{ resource_id: resourceId \}/)
  assert.match(detailPageSource, /resourceFieldCount/)
  assert.match(detailPageSource, /onFieldsChange=\{handleResourceFieldsChange\}/)
  assert.doesNotMatch(detailPageSource, /metainfo\.field_count/)
})

test('安全管控详情页使用 tab 展示并将当前 tab 写入 URL', () => {
  assert.match(detailPageSource, /type SecurityGovernanceDetailTabKey = 'overview' \| 'resourceFields' \| 'physicalTable' \| 'apiInfo' \| 'accessSubjects' \| 'accessPolicies' \| 'homomorphic' \| 'accessInfo' \| 'status' \| 'lineage'/)
  assert.match(detailPageSource, /const requestedTab = searchParams\.get\('tab'\) as SecurityGovernanceDetailTabKey \| null/)
  assert.match(detailPageSource, /const detailTabs: Array<\[SecurityGovernanceDetailTabKey, string\]> = \[/)
  assert.match(detailPageSource, /\['overview', '基本信息'\]/)
  assert.match(detailPageSource, /\['resourceFields', '资源字段'\]/)
  assert.match(detailPageSource, /\['physicalTable', '接入规则'\]/)
  assert.match(detailPageSource, /\['apiInfo', 'API 信息'\]/)
  assert.match(detailPageSource, /\['accessSubjects', '数据应用'\]/)
  assert.match(detailPageSource, /\['accessPolicies', '访问策略'\]/)
  assert.match(detailPageSource, /\['homomorphic', '同态加密'\]/)
  assert.doesNotMatch(detailPageSource, /\['accessInfo', '安全接入'\]/)
  assert.match(detailPageSource, /requestedTab === 'accessInfo' \? 'physicalTable' : requestedTab/)
  assert.match(detailPageSource, /\['lineage', '血缘关系'\]/)
  assert.match(detailPageSource, /\['status', '安全状态'\]/)
  assert.match(detailPageSource, /const handleTabChange = \(tabKey: SecurityGovernanceDetailTabKey\) => \{/)
  assert.match(detailPageSource, /pathname: location\.pathname/)
  assert.match(detailPageSource, /search: `\?\$\{buildTabSearchParams\(tabKey\)\.toString\(\)\}`/)
  assert.match(detailPageSource, /replace: true/)
  assert.match(detailPageSource, /state: locationState \?\? undefined/)
  assert.match(detailPageSource, /<ResourceFieldsPanel[\s\S]*resourceId=\{item\.id\}[\s\S]*homomorphicFieldCodes=\{securityRelations\.homomorphicFieldCodes\}/)
  assert.match(detailPageSource, /LineageRelationGraph/)
  assert.match(detailPageSource, /数据安全血缘关系/)
})

test('资源详情 tab 在亮色背景下保持可读对比度', () => {
  assert.match(detailPageSource, /aria-label="数据资源详情导航"/)
  assert.match(detailPageSource, /role="tablist"/)
  assert.match(detailPageSource, /bg-\[color-mix\(in_srgb,var\(--surface-raised-strong\)_94%,transparent\)\]/)
  assert.match(detailPageSource, /font-medium text-\[var\(--text-main\)\]/)
  assert.match(detailPageSource, /aria-selected=\{activeTab === key\}/)
})

test('资源详情数据应用 tab 直接维护当前唯一 API 的主体授权', () => {
  assert.match(detailPageSource, /activeTab === 'accessSubjects'/)
  assert.match(detailPageSource, /<ResourceAccessSubjectsPanel resourceId=\{String\(item\.id\)\} canManage=\{canManageResources\}/)
  assert.match(resourceAccessSubjectsPanelSource, /ensureDefaultSecurityApi\(resourceId\)/)
  assert.match(resourceAccessSubjectsPanelSource, /listSecurityV3Records\('security_access_subjects'/)
  assert.match(resourceAccessSubjectsPanelSource, /hasApiAuthorization\(subject\.allowed_api_codes_json, apiCode\)/)
  assert.match(resourceAccessSubjectsPanelSource, /updateSecurityV3Record\('security_access_subjects', subjectId/)
  assert.match(resourceAccessSubjectsPanelSource, /allowed_api_codes_json: allowedApiCodes/)
  assert.match(resourceAccessSubjectsPanelSource, /添加数据应用/)
  assert.match(resourceAccessSubjectsPanelSource, /已授权数据应用/)
  assert.match(resourceAccessSubjectsPanelSource, /取消授权/)
  assert.match(resourceAccessSubjectsPanelSource, /确认取消/)
  assert.match(resourceAccessSubjectsPanelSource, /保留授权/)
  assert.doesNotMatch(resourceAccessSubjectsPanelSource, /window\.confirm/)
  assert.match(resourceAccessSubjectsPanelSource, /仍需存在已发布且场景匹配的访问策略/)
  assert.doesNotMatch(resourceAccessSubjectsPanelSource, /行为基线/)
  assert.doesNotMatch(resourceAccessSubjectsPanelSource, /security_behavior_baselines/)
  assert.doesNotMatch(runtimeClientSource, /behavior-baseline/)
  assert.match(resourceAccessSubjectsSource, /codes\.includes\('\*'\) \|\| codes\.includes\(target\)/)
  assert.match(resourceAccessSubjectsSource, /grantApiAuthorization/)
  assert.match(resourceAccessSubjectsSource, /revokeApiAuthorization/)
})

test('资源详情按真实关系聚合 API、数据源、接入安全和运行字段引用', () => {
  assert.match(relationSource, /listSecurityV3Records\('eco_resource_security_fields'/)
  assert.match(relationSource, /listSecurityV3Records\('security_api_resources'/)
  assert.match(relationSource, /listSecurityV3Records\('security_data_sources'/)
  assert.match(relationSource, /listSecurityV3Records\('security_ingest_logs'/)
  assert.match(relationSource, /listSecurityV3Records\('security_policy_decision_logs'/)
  assert.match(relationSource, /listSecurityV3Records\('eco_resource_security_policies'/)
  assert.match(relationSource, /listSecurityV3Records\('security_confidential_tasks'/)
  assert.match(detailPageSource, /activeTab === 'apiInfo'/)
  assert.match(detailPageSource, /activeTab === 'physicalTable'/)
  assert.match(detailPageSource, /传输保护/)
  assert.match(detailPageSource, /完整性校验/)
  assert.match(detailPageSource, /最近接入规则执行日志/)
})

test('每个数据资源自动生成唯一 API 并只管理上下线', () => {
  assert.match(detailPageSource, /<ResourceApisPanel/)
  assert.match(resourceApisPanelSource, /ensureDefaultSecurityApi\(resourceId\)/)
  assert.match(resourceApisPanelSource, /listSecurityV3Records\('security_api_resources'/)
  assert.match(resourceApisPanelSource, /publishSecurityApi/)
  assert.match(resourceApisPanelSource, /unpublishSecurityApi/)
  assert.doesNotMatch(resourceApisPanelSource, /SecurityV3CollectionPage/)
  assert.match(resourceApisPanelSource, /API 访问地址/)
  assert.match(resourceApisPanelSource, /请求参数说明/)
  assert.match(resourceApisPanelSource, /访问鉴权/)
  assert.match(resourceApisPanelSource, /访问示例代码/)
  assert.match(resourceApisPanelSource, /X-API-Key: \$API_KEY/)
  assert.match(resourceApisPanelSource, /curl.*python.*javascript/s)
  assert.match(runtimeClientSource, /\/management\/resources\/\$\{encodeURIComponent\(resourceId\)\}\/default-api/)
  assert.match(runtimeClientSource, /\/management\/apis\/\$\{encodeURIComponent\(id\)\}\/unpublish/)
})

test('新建数据资源可定义只读 SQL 和 API 默认参数', () => {
  assert.match(resourceEditDialogSource, /数据查询与 API 参数/)
  assert.match(resourceEditDialogSource, /基准物理表/)
  assert.match(resourceEditDialogSource, /自定义查询 SQL（可选）/)
  assert.match(resourceEditDialogSource, /:paramName/)
  assert.match(resourceEditDialogSource, /queryDefaultParamsText/)
  assert.match(resourceEditSource, /api_query:/)
  assert.match(resourceEditSource, /query_sql: values\.querySql\.trim\(\)/)
  assert.match(resourceEditSource, /default_params: queryDefaultParams/)
})

test('数据资源标签读写兼容运行时使用的资源标签字段', () => {
  assert.match(resourceEditDialogSource, /资源标签/)
  assert.match(resourceEditDialogSource, /用于分类分级与标签补全/)
  assert.match(resourceEditDialogSource, /splitTags\(tagsText\)\.length === 0/)
  assert.match(resourceEditSource, /tags: normalizeTags\(raw\.resource_tags \?\? raw\.tags\)/)
  assert.match(resourceEditSource, /tags: values\.tags/)
  assert.match(resourceEditSource, /resource_tags: values\.tags/)
})

test('资源详情提供真实可执行的安全访问策略配置', () => {
  assert.match(detailPageSource, /<ResourceAccessPoliciesPanel/)
  assert.match(accessPoliciesPanelSource, /collection: 'eco_resource_security_policies'/)
  assert.match(accessPoliciesPanelSource, /policy_kind: 'access_policy'/)
  assert.match(accessPoliciesPanelSource, /name: 'subject_id'/)
  assert.match(accessPoliciesPanelSource, /name: 'api_resource_id'/)
  assert.doesNotMatch(accessPoliciesPanelSource, /name: 'field_allowlist_json'/)
  assert.match(accessPoliciesPanelSource, /name: 'abnormal_access_rules_json'/)
  assert.match(accessPoliciesPanelSource, /name: 'max_requests_per_minute'/)
  assert.match(accessPoliciesPanelSource, /name: 'risk_threshold'/)
  assert.match(accessPoliciesPanelSource, /publishSecurityPolicy/)
  assert.match(accessPoliciesPanelSource, /listSecurityV3Records\('security_policy_decision_logs'/)
  assert.match(accessPoliciesPanelSource, /访问策略最近执行日志/)
  assert.match(accessPoliciesPanelSource, /风险依据/)
  assert.match(accessPoliciesPanelSource, /applied_limits_json/)
  assert.match(accessPoliciesPanelSource, /matchedLabels/)
  assert.match(accessPoliciesPanelSource, /runtimeTraceRecords/)
  assert.match(accessPoliciesPanelSource, /labelEnrichment\.matchedLabels/)
  assert.match(accessPoliciesPanelSource, /riskFactors/)
  assert.match(accessPoliciesPanelSource, /fieldTagSummary/)
  assert.match(accessPoliciesPanelSource, /policyEvaluations/)
  assert.match(accessPoliciesPanelSource, /accessPath/)
  assert.match(accessPoliciesPanelSource, /访问链路/)
  assert.match(accessPoliciesPanelSource, /formatRequestTime\(log\.requested_at \|\| log\.createdAt\)/)
  assert.match(accessPoliciesPanelSource, /new Date\(normalized\)/)
  assert.doesNotMatch(accessPoliciesPanelSource, /requested_at[^\n]*slice\(0, 19\)/)
})

test('资源详情提供不保存私钥和明文值的同态任务配置', () => {
  assert.match(detailPageSource, /<ResourceHomomorphicPanel/)
  assert.match(homomorphicPanelSource, /collection: 'security_confidential_tasks'/)
  assert.match(homomorphicPanelSource, /name: 'subject_id'/)
  assert.match(homomorphicPanelSource, /name: 'api_resource_id'/)
  assert.match(homomorphicPanelSource, /name: 'measure_field_code'/)
  assert.match(homomorphicPanelSource, /name: 'crypto_key_id'/)
  assert.match(homomorphicPanelSource, /任务配置不保存私钥、Secret 或原始明文值/)
  assert.doesNotMatch(homomorphicPanelSource, /name: 'private_key'/)
  assert.doesNotMatch(homomorphicPanelSource, /name: 'values'/)
  assert.match(homomorphicPanelSource, /同态加密最近执行日志/)
  assert.match(homomorphicPanelSource, /summary\.events/)
  assert.match(homomorphicPanelSource, /summary\.logs/)
})

test('接入规则的数据源信息以单行全宽卡片横向铺开', () => {
  assert.match(detailPageSource, /title="接入规则"/)
  assert.match(detailPageSource, /securityRelations\.sources\.map[\s\S]*mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4/)
  assert.doesNotMatch(detailPageSource, /mt-5 grid gap-4 xl:grid-cols-2[\s\S]*securityRelations\.sources\.map/)
})

test('数据资源可配置覆盖数据源默认值的接入校验规则', () => {
  assert.match(detailPageSource, /配置资源校验/)
  assert.match(detailPageSource, /<ResourceIngestValidationDialog/)
  assert.match(resourceIngestValidationDialogSource, /继承数据源字段校验规则/)
  assert.match(resourceIngestValidationDialogSource, /按资源摘要字段校验/)
  assert.match(resourceIngestValidationDialogSource, /摘要字段/)
  assert.match(resourceIngestValidationDialogSource, /参与摘要的字段/)
  assert.match(resourceIngestValidationDialogSource, /拒绝该记录/)
  assert.match(resourceIngestValidationDialogSource, /createPortal/)
  assert.match(resourceIngestValidationDialogSource, /document\.body/)
  assert.match(resourceIngestValidationSource, /stat_base:/)
  assert.match(resourceIngestValidationSource, /ingest_validation: config/)
  assert.match(resourcePhysicalTablePanelSource, /resource.*资源级规则已生效/s)
  assert.match(resourcePhysicalTablePanelSource, /integrityExecutable/)
  assert.match(securityV3PagesSource, /resource_delivery_validation: '资源交付校验'/)
  assert.match(securityV3PagesSource, /value: 'warning', label: '告警放行'/)
})

test('资源字段页同时维护基础字段与字段安全档案', () => {
  assert.doesNotMatch(resourceFieldsPanelSource, /label: '策略引擎'/)
  assert.match(resourceFieldsPanelSource, /label: '同态计算'/)
  assert.match(resourceFieldsPanelSource, /collection: 'eco_resource_security_fields'/)
  assert.match(resourceFieldsPanelSource, /name: 'important_field_flag'/)
  assert.match(resourceFieldsPanelSource, /name: 'security_level'/)
  assert.match(resourceFieldsPanelSource, /name: 'information_category'/)
  assert.match(resourceFieldsPanelSource, /name: 'classification_level'/)
  assert.match(resourceFieldsPanelSource, /name: 'field_tags'/)
  assert.match(resourceFieldsPanelSource, /name: 'required_desensitization'/)
  assert.match(resourceFieldsPanelSource, /name: 'output_allowed'/)
  assert.doesNotMatch(resourceFieldsPanelSource, /name: 'required_access_scope'/)
  assert.doesNotMatch(resourceFieldsPanelSource, /name: 'required_export_allowed'/)
  assert.doesNotMatch(resourceFieldsPanelSource, /name: 'required_approval_required'/)
})

test('安全管控详情页与数据接入和日志审计模块口径保持一致', () => {
  assert.match(detailPageSource, /function ModuleAlignmentStrip/)
  assert.match(detailPageSource, /数据接入管理一致口径/)
  assert.match(detailPageSource, /数据源配置/)
  assert.match(detailPageSource, /接入规则配置/)
  assert.match(detailPageSource, /接入状态/)
  assert.match(detailPageSource, /\/security-governance\/ingest\/sources/)
  assert.match(detailPageSource, /\/security-governance\/ingest\/validation-rules/)
  assert.doesNotMatch(detailPageSource, /\/security-governance\/ingest\/logs/)
  assert.doesNotMatch(detailPageSource, /访问控制管理一致口径/)
  assert.doesNotMatch(detailPageSource, /数据同态加密一致口径/)
  assert.match(detailPageSource, /日志链路审计一致口径/)
  assert.match(detailPageSource, /完整版访问日志/)
  assert.match(detailPageSource, /\/security-governance\/logs/)
  assert.doesNotMatch(detailPageSource, /操作链路追溯/)
  assert.doesNotMatch(detailPageSource, /审计报告生成/)
  assert.doesNotMatch(detailPageSource, /\/security-governance\/audit\/trace/)
  assert.doesNotMatch(detailPageSource, /\/security-governance\/audit\/report/)
})

test('基本信息只保留资源基础信息并使用真实运行指标', () => {
  assert.match(detailPageSource, /资源编码/)
  assert.match(detailPageSource, /数据类型/)
  assert.doesNotMatch(detailPageSource, /资源状态/)
  assert.match(detailPageSource, /数据分类/)
  assert.match(detailPageSource, /业务分类/)
  assert.match(detailPageSource, /来源单位/)
  assert.match(detailPageSource, /来源系统/)
  assert.match(detailPageSource, /更新周期/)
  assert.match(detailPageSource, /title: '字段数量'/)
  assert.match(detailPageSource, /resourceFieldCount/)
  assert.match(detailPageSource, /title: 'API 访问次数'/)
  assert.match(detailPageSource, /securityRelations\.decisionLogs\.length/)
  assert.match(detailPageSource, /title: '访问策略数量'/)
  assert.match(detailPageSource, /title: '接入抽样数量'/)
  assert.match(detailPageSource, /latestStatRecord\.metainfo\.record_count/)
  assert.doesNotMatch(detailPageSource, /<TopicPill>资源编码：/)
  assert.doesNotMatch(detailPageSource, /<TopicPill>来源单位：/)
  assert.doesNotMatch(detailPageSource, /<TopicPill>来源系统：/)
  assert.doesNotMatch(detailPageSource, /<TopicPill>资源状态：/)
  assert.doesNotMatch(detailPageSource, /安全档案编号/)
  assert.doesNotMatch(detailPageSource, /安全分类：/)
  assert.doesNotMatch(detailPageSource, /安全等级：/)
  assert.doesNotMatch(detailPageSource, /管控标识/)
  assert.doesNotMatch(detailPageSource, /安全责任人/)
  assert.doesNotMatch(detailPageSource, /共享范围/)
  assert.doesNotMatch(detailPageSource, /审批模式/)
  assert.doesNotMatch(detailPageSource, /导出范围/)
  assert.doesNotMatch(detailPageSource, /复核计划/)
  assert.doesNotMatch(detailPageSource, /定级依据/)
})
