import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const detailPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-governance-detail-page.tsx'), 'utf8')
const editDialogSource = readFileSync(resolve(process.cwd(), 'src/components/security-governance-edit-dialog.tsx'), 'utf8')

test('安全管控详情页支持返回原列表并兜底跳回安全管控首页', () => {
  assert.match(detailPageSource, /type SecurityGovernanceDetailLocationState = \{/)
  assert.match(detailPageSource, /const returnTo = typeof locationState\?\.returnTo === 'string'/)
  assert.match(detailPageSource, /const handleGoBack = \(\) => \{/)
  assert.match(detailPageSource, /if \(returnTo\) \{/)
  assert.match(detailPageSource, /navigate\(returnTo\)/)
  assert.match(detailPageSource, /navigate\(-1\)/)
  assert.match(detailPageSource, /navigate\(withEmbed\('\/security-governance'\)\)/)
  assert.match(detailPageSource, /返回安全管控/)
})

test('安全管控详情页保留跳转资源目录详情入口', () => {
  assert.match(detailPageSource, /useSecurityGovernancePolicyDetail\(id, true\)/)
  assert.match(detailPageSource, /to=\{withEmbed\(`\/catalog\/\$\{item\.id\}`\)\}/)
  assert.match(detailPageSource, /资源目录详情/)
  assert.match(detailPageSource, /编辑资源/)
  assert.match(detailPageSource, /编辑字段/)
  assert.match(detailPageSource, /SecurityGovernanceProfileEditDialog/)
  assert.match(detailPageSource, /SecurityGovernanceFieldEditDialog/)
  assert.doesNotMatch(detailPageSource, /<ResourceEditDialog/)
  assert.doesNotMatch(detailPageSource, /<DataItemsEditDialog/)
})

test('安全管控详情页使用 tab 展示并将当前 tab 写入 URL', () => {
  assert.match(detailPageSource, /type SecurityGovernanceDetailTabKey = 'overview' \| 'fieldSecurity' \| 'status' \| 'physicalTables' \| 'latestPreview' \| 'lineage'/)
  assert.match(detailPageSource, /const requestedTab = searchParams\.get\('tab'\) as SecurityGovernanceDetailTabKey \| null/)
  assert.match(detailPageSource, /const detailTabs: Array<\[SecurityGovernanceDetailTabKey, string\]> = \[/)
  assert.match(detailPageSource, /\['overview', '安全管控信息'\]/)
  assert.match(detailPageSource, /\['fieldSecurity', '字段安全'\]/)
  assert.match(detailPageSource, /\['lineage', '血缘关系'\]/)
  assert.match(detailPageSource, /\['status', '安全状态'\]/)
  assert.match(detailPageSource, /\['physicalTables', '物理表'\]/)
  assert.match(detailPageSource, /\['latestPreview', '最新预览'\]/)
  assert.match(detailPageSource, /const handleTabChange = \(tabKey: SecurityGovernanceDetailTabKey\) => \{/)
  assert.match(detailPageSource, /pathname: location\.pathname/)
  assert.match(detailPageSource, /search: `\?\$\{buildTabSearchParams\(tabKey\)\.toString\(\)\}`/)
  assert.match(detailPageSource, /replace: true/)
  assert.match(detailPageSource, /state: locationState \?\? undefined/)
  assert.match(detailPageSource, /字段安全/)
  assert.match(detailPageSource, /字段分类分级/)
  assert.match(detailPageSource, /字段安全策略/)
  assert.match(detailPageSource, /LineageRelationGraph/)
  assert.match(detailPageSource, /数据安全血缘关系/)
})

test('安全管控详情页三块核心信息与数据接入、访问控制、日志审计模块口径保持一致', () => {
  assert.match(detailPageSource, /function ModuleAlignmentStrip/)
  assert.match(detailPageSource, /数据接入管理一致口径/)
  assert.match(detailPageSource, /数据源配置/)
  assert.match(detailPageSource, /接入规则配置/)
  assert.match(detailPageSource, /接入监控/)
  assert.match(detailPageSource, /\/security-governance\/data-access\/source-config/)
  assert.match(detailPageSource, /\/security-governance\/data-access\/rule-config/)
  assert.match(detailPageSource, /\/security-governance\/data-access\/monitoring/)
  assert.match(detailPageSource, /访问控制管理一致口径/)
  assert.match(detailPageSource, /数据分类分级/)
  assert.match(detailPageSource, /策略引擎配置/)
  assert.match(detailPageSource, /\/security-governance\/access-control\/classification/)
  assert.match(detailPageSource, /\/security-governance\/access-control\/policy-engine/)
  assert.match(detailPageSource, /数据同态加密一致口径/)
  assert.match(detailPageSource, /数据同态加密/)
  assert.match(detailPageSource, /\/security-governance\/homomorphic-encryption/)
  assert.match(detailPageSource, /日志链路审计一致口径/)
  assert.match(detailPageSource, /日志链路审计/)
  assert.match(detailPageSource, /\/security-governance\/audit\/log-query/)
  assert.doesNotMatch(detailPageSource, /操作链路追溯/)
  assert.doesNotMatch(detailPageSource, /审计报告生成/)
  assert.doesNotMatch(detailPageSource, /\/security-governance\/audit\/trace/)
  assert.doesNotMatch(detailPageSource, /\/security-governance\/audit\/report/)
})

test('安全管控详情页展示安全总表字段且不直出大 JSON 信息块', () => {
  assert.match(detailPageSource, /数据分类/)
  assert.match(detailPageSource, /业务分类/)
  assert.match(detailPageSource, /数据接入来源/)
  assert.match(detailPageSource, /物理表数量/)
  assert.match(detailPageSource, /基准表/)
  assert.match(detailPageSource, /业务时间字段/)
  assert.match(detailPageSource, /安全分类/)
  assert.match(detailPageSource, /安全等级/)
  assert.match(detailPageSource, /管控标识/)
  assert.match(detailPageSource, /安全责任部门/)
  assert.match(detailPageSource, /安全责任人/)
  assert.match(detailPageSource, /共享范围/)
  assert.match(detailPageSource, /访问范围/)
  assert.match(detailPageSource, /审批模式/)
  assert.match(detailPageSource, /脱敏方式/)
  assert.match(detailPageSource, /导出范围/)
  assert.match(detailPageSource, /API 鉴权方式/)
  assert.match(detailPageSource, /复核计划/)
  assert.match(detailPageSource, /定级依据/)
  assert.match(detailPageSource, /风险说明/)
  assert.doesNotMatch(detailPageSource, /生态环境信息分类/)
  assert.doesNotMatch(detailPageSource, /数据主体类型/)
  assert.doesNotMatch(detailPageSource, /重要数据标识/)
  assert.doesNotMatch(detailPageSource, /核心管控对象标识/)
  assert.doesNotMatch(detailPageSource, /要求开放控制/)
  assert.doesNotMatch(detailPageSource, /要求外部共享/)
  assert.doesNotMatch(detailPageSource, /要求审批'/)
  assert.doesNotMatch(detailPageSource, /要求脱敏'/)
  assert.doesNotMatch(detailPageSource, /档案状态/)
  assert.doesNotMatch(detailPageSource, /资源安全档案摘要/)
  assert.doesNotMatch(detailPageSource, /字段安全摘要/)
  assert.doesNotMatch(detailPageSource, /安全复核记录/)
  assert.doesNotMatch(detailPageSource, /资源安全档案 JSON/)
  assert.doesNotMatch(detailPageSource, /字段安全档案 JSON/)
  assert.doesNotMatch(detailPageSource, /字段安全策略 JSON/)
  assert.doesNotMatch(detailPageSource, /安全复核记录 JSON/)
})

test('字段安全编辑弹窗只允许维护安全相关信息', () => {
  assert.match(editDialogSource, /字段基础信息已预置，这里只允许维护安全相关信息/)
  assert.match(editDialogSource, /字段编码/)
  assert.match(editDialogSource, /字段名称/)
  assert.doesNotMatch(editDialogSource, /新增/)
  assert.doesNotMatch(editDialogSource, /删除/)
  assert.doesNotMatch(editDialogSource, /业务时间字段/)
  assert.doesNotMatch(editDialogSource, /基准表/)
})
