import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const securityGovernanceRoutesSource = readFileSync(resolve(process.cwd(), 'src/modules/SecurityGovernance/routes.tsx'), 'utf8')
const navigationSource = readFileSync(resolve(process.cwd(), 'src/lib/nocobase-portal-navigation.ts'), 'utf8')
const portalContextSource = readFileSync(resolve(process.cwd(), 'src/lib/portal-context.tsx'), 'utf8')
const accessControlTabsSource = readFileSync(resolve(process.cwd(), 'src/components/security-access-control-tabs.tsx'), 'utf8')
const securityDashboardPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-dashboard-page.tsx'), 'utf8')
const securityDataLabelsPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-data-labels-page.tsx'), 'utf8')
const securityLogQueryPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-log-query-page.tsx'), 'utf8')
const securityPolicyEnginePageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-policy-engine-page.tsx'), 'utf8')
const securityAccessRuleConfigPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-access-rule-config-page.tsx'), 'utf8')
const securityAccessMonitoringPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-access-monitoring-page.tsx'), 'utf8')
const securityConfidentialComputingPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-confidential-computing-page.tsx'), 'utf8')
const securityHomomorphicLogsPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-homomorphic-logs-page.tsx'), 'utf8')
const homomorphicTabsSource = readFileSync(resolve(process.cwd(), 'src/components/security-homomorphic-tabs.tsx'), 'utf8')
const securityPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-governance-page.tsx'), 'utf8')
const securityDetailPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-governance-detail-page.tsx'), 'utf8')
const securityRuntimeSource = readFileSync(resolve(process.cwd(), 'src/lib/nocobase-security-runtime.ts'), 'utf8')
const seedDemoSource = readFileSync(resolve(process.cwd(), 'scripts/seed-nocobase-demo.mjs'), 'utf8')
const viteConfigSource = readFileSync(resolve(process.cwd(), 'vite.config.ts'), 'utf8')
const openFheMainSource = readFileSync(resolve(process.cwd(), 'openfhe-service/app/main.py'), 'utf8')
const openFheCryptoSource = readFileSync(resolve(process.cwd(), 'openfhe-service/app/crypto.py'), 'utf8')
const dockerComposeSource = readFileSync(resolve(process.cwd(), 'docker/docker-compose.yml'), 'utf8')
const securityGovernanceDataSource = readFileSync(resolve(process.cwd(), 'src/lib/nocobase-security-governance.ts'), 'utf8')

test('数据安全管控看板注册为模块首页，资源列表保留独立路由', () => {
  assert.match(securityGovernanceRoutesSource, /const SecurityDashboardPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-dashboard-page'\)\)\.SecurityDashboardPage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecurityDataLabelsPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-data-labels-page'\)\)\.SecurityDataLabelsPage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecuritySourceConfigPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-source-config-page'\)\)\.SecuritySourceConfigPage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecurityAccessRuleConfigPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-access-rule-config-page'\)\)\.SecurityAccessRuleConfigPage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecurityAccessMonitoringPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-access-monitoring-page'\)\)\.SecurityAccessMonitoringPage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecurityLogQueryPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-log-query-page'\)\)\.SecurityLogQueryPage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecurityPolicyEnginePage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-policy-engine-page'\)\)\.SecurityPolicyEnginePage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecurityConfidentialComputingPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-confidential-computing-page'\)\)\.SecurityConfidentialComputingPage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecurityHomomorphicLogsPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-homomorphic-logs-page'\)\)\.SecurityHomomorphicLogsPage \}\)\)/)
  assert.doesNotMatch(securityGovernanceRoutesSource, /SecurityAccessApprovalPage/)
  assert.doesNotMatch(securityGovernanceRoutesSource, /security-access-approval-page/)
  assert.doesNotMatch(securityGovernanceRoutesSource, /SecurityTracePage/)
  assert.doesNotMatch(securityGovernanceRoutesSource, /SecurityAuditReportPage/)
  assert.doesNotMatch(securityGovernanceRoutesSource, /SecurityVersionManagementPage/)
  assert.doesNotMatch(securityGovernanceRoutesSource, /SecurityFeaturePlaceholderPage/)
  assert.match(securityGovernanceRoutesSource, /const SecurityGovernancePage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-governance-page'\)\)\.SecurityGovernancePage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /const SecurityGovernanceDetailPage = lazy\(async \(\) => \(\{ default: \(await import\('\.\.\/\.\.\/pages\/security-governance-detail-page'\)\)\.SecurityGovernanceDetailPage \}\)\)/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance" element={<Navigate to="\/security-governance\/dashboard" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/dashboard" element={<SecurityDashboardPage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/data-access" element={<Navigate to="\/security-governance\/data-access\/source-config" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/data-access\/source-config" element={<SecuritySourceConfigPage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/data-access\/rule-config" element={<SecurityAccessRuleConfigPage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/data-access\/monitoring" element={<SecurityAccessMonitoringPage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/access-control" element={<Navigate to="\/security-governance\/access-control\/classification" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/access-control\/classification" element={<SecurityDataLabelsPage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/access-control\/policy-engine" element={<SecurityPolicyEnginePage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/access-control\/role-permission" element={<Navigate to="\/security-governance\/access-control\/policy-engine" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/access-control\/approval" element={<Navigate to="\/security-governance\/access-control\/policy-engine" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/access-control\/confidential-computing" element={<Navigate to="\/security-governance\/homomorphic-encryption" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/homomorphic-encryption" element={<SecurityConfidentialComputingPage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/homomorphic-encryption\/engine" element={<Navigate to="\/security-governance\/homomorphic-encryption" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/homomorphic-encryption\/logs" element={<SecurityHomomorphicLogsPage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/homomorphic-engine" element={<Navigate to="\/security-governance\/homomorphic-encryption" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/homomorphic-logs" element={<Navigate to="\/security-governance\/homomorphic-encryption\/logs" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/confidential-computing" element={<Navigate to="\/security-governance\/homomorphic-encryption" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/audit" element={<Navigate to="\/security-governance\/audit\/log-query" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/audit\/log-query" element={<SecurityLogQueryPage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/audit\/trace" element={<Navigate to="\/security-governance\/audit\/log-query" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/audit\/report" element={<Navigate to="\/security-governance\/audit\/log-query" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/config" element={<Navigate to="\/security-governance\/access-control\/classification" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/config\/data-labels" element={<Navigate to="\/security-governance\/access-control\/classification" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/config\/system-params" element={<Navigate to="\/security-governance\/dashboard" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/config\/version" element={<Navigate to="\/security-governance\/dashboard" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/source-config" element={<Navigate to="\/security-governance\/data-access\/source-config" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/data-labels" element={<Navigate to="\/security-governance\/access-control\/classification" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/policy-engine" element={<Navigate to="\/security-governance\/access-control\/policy-engine" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/confidential" element={<Navigate to="\/security-governance\/homomorphic-encryption" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/trace" element={<Navigate to="\/security-governance\/audit\/log-query" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/log-query" element={<Navigate to="\/security-governance\/audit\/log-query" replace \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/resources" element={<SecurityGovernancePage \/>} \/>/)
  assert.match(securityGovernanceRoutesSource, /<Route path="\/security-governance\/:id" element={<SecurityGovernanceDetailPage \/>} \/>/)
  assert.match(navigationSource, /\{ key: 'nav_security_dashboard', title: '安全态势看板', target: '\/security-governance\/dashboard', icon: Shield \}/)
  assert.match(navigationSource, /\{ key: 'nav_data_access', title: '数据接入管理', target: '\/security-governance\/data-access\/source-config', icon: DatabaseZap \}/)
  assert.match(navigationSource, /\{ key: 'nav_resource_control', title: '数据资源管控', target: '\/security-governance\/resources', icon: Database \}/)
  assert.match(navigationSource, /\{ key: 'nav_access_control', title: '访问控制管理', target: '\/security-governance\/access-control\/classification', icon: Workflow \}/)
  assert.match(navigationSource, /\{ key: 'nav_homomorphic_encryption', title: '数据同态加密', target: '\/security-governance\/homomorphic-encryption', icon: LockKeyhole \}/)
  assert.doesNotMatch(navigationSource, /key: 'nav_audit'/)
  assert.match(navigationSource, /EXCLUDED_PRIMARY_NAV_TARGETS = new Set\(\[[\s\S]*'\/security-governance\/audit\/log-query'[\s\S]*\]\)/)
  assert.doesNotMatch(navigationSource, /nav_config/)
  assert.doesNotMatch(navigationSource, /title: '数据标签管理'[\s\S]*target: '\/security-governance\/config\/data-labels'/)
  assert.doesNotMatch(navigationSource, /nav_data_labels/)
  assert.doesNotMatch(navigationSource, /nav_policy_engine/)
  assert.doesNotMatch(navigationSource, /nav_trace/)
  assert.doesNotMatch(navigationSource, /nav_log_query/)
})

test('日志链路审计收敛为日志查询，不再暴露追溯和报告入口', () => {
  assert.match(securityLogQueryPageSource, /export function SecurityLogQueryPage\(\)/)
  assert.match(securityLogQueryPageSource, /AccessControlSecondaryTabs/)
  assert.match(securityLogQueryPageSource, /<AccessControlSecondaryTabs[\s\S]*actions=\{/)
  assert.match(accessControlTabsSource, /日志链路审计/)
  assert.match(securityLogQueryPageSource, /AuditQueryActions/)
  assert.doesNotMatch(securityLogQueryPageSource, /auditSecondaryNavItems/)
  assert.doesNotMatch(securityLogQueryPageSource, /AuditSecondaryTabs/)
  assert.doesNotMatch(securityLogQueryPageSource, /aria-label="日志链路审计二级导航"/)
  assert.doesNotMatch(securityLogQueryPageSource, /操作链路追溯/)
  assert.doesNotMatch(securityLogQueryPageSource, /审计报告生成/)
  assert.doesNotMatch(securityLogQueryPageSource, /\/security-governance\/audit\/trace/)
  assert.doesNotMatch(securityLogQueryPageSource, /\/security-governance\/audit\/report/)
})

test('访问控制管理二级导航包含分类分级、策略引擎和日志链路审计', () => {
  assert.match(accessControlTabsSource, /accessControlSecondaryNavItems/)
  assert.match(accessControlTabsSource, /数据分类分级[\s\S]*策略引擎配置[\s\S]*日志链路审计/)
  assert.doesNotMatch(accessControlTabsSource, /密态计算管理/)
  assert.doesNotMatch(accessControlTabsSource, /数据同态加密/)
  assert.match(accessControlTabsSource, /\/security-governance\/access-control\/classification/)
  assert.match(accessControlTabsSource, /\/security-governance\/access-control\/policy-engine/)
  assert.match(accessControlTabsSource, /\/security-governance\/audit\/log-query/)
  assert.match(accessControlTabsSource, /pathname\.includes\('\/audit\/log-query'\)/)
  assert.doesNotMatch(accessControlTabsSource, /\/security-governance\/access-control\/confidential-computing/)
  assert.match(accessControlTabsSource, /aria-label="访问控制管理二级导航"/)
  assert.match(accessControlTabsSource, /actions/)
  assert.match(accessControlTabsSource, /xl:justify-between/)
  assert.match(accessControlTabsSource, /xl:justify-end/)
  assert.doesNotMatch(accessControlTabsSource, /访问申请审批/)
  assert.doesNotMatch(accessControlTabsSource, /角色权限管理/)
  assert.match(securityDataLabelsPageSource, /AccessControlSecondaryTabs actions=\{labelActions\}/)
  assert.match(securityPolicyEnginePageSource, /<AccessControlSecondaryTabs[\s\S]*actions=\{/)
  assert.match(securityLogQueryPageSource, /<AccessControlSecondaryTabs[\s\S]*actions=\{/)
  assert.doesNotMatch(securityConfidentialComputingPageSource, /AccessControlSecondaryTabs/)
  assert.doesNotMatch(securityPolicyEnginePageSource, /\/security-governance\/access-control\/approval/)
  assert.doesNotMatch(securityPolicyEnginePageSource, /\/security-governance\/access-control\/role-permission/)
})

test('策略引擎配置实现 policy_engine_screen_plan 的核心区块', () => {
  assert.match(securityPolicyEnginePageSource, /export function SecurityPolicyEnginePage\(\)/)
  assert.match(securityPolicyEnginePageSource, /buildPolicyEngineRows/)
  assert.match(securityPolicyEnginePageSource, /joinSecurityGovernanceItems/)
  assert.match(securityPolicyEnginePageSource, /AccessControlSecondaryTabs/)
  assert.match(securityPolicyEnginePageSource, /策略引擎配置/)
  assert.doesNotMatch(securityPolicyEnginePageSource, /访问申请审批/)
  assert.doesNotMatch(securityPolicyEnginePageSource, /角色权限管理/)
  assert.match(securityPolicyEnginePageSource, /新建策略/)
  assert.doesNotMatch(securityPolicyEnginePageSource, /导入策略模板/)
  assert.doesNotMatch(securityPolicyEnginePageSource, /批量操作/)
  assert.match(securityPolicyEnginePageSource, /策略引擎运行状态/)
  assert.match(securityPolicyEnginePageSource, /活跃策略数/)
  assert.match(securityPolicyEnginePageSource, /今日拦截次数/)
  assert.match(securityPolicyEnginePageSource, /规则执行性能/)
  assert.match(securityPolicyEnginePageSource, /搜索策略名称、描述、创建人/)
  assert.match(securityPolicyEnginePageSource, /访问控制策略/)
  assert.match(securityPolicyEnginePageSource, /分层隔离策略/)
  assert.match(securityPolicyEnginePageSource, /异常检测策略/)
  assert.match(securityPolicyEnginePageSource, /自定义策略/)
  assert.match(securityPolicyEnginePageSource, /生效范围/)
  assert.match(securityPolicyEnginePageSource, /拦截次数/)
  assert.match(securityPolicyEnginePageSource, /PolicyDrawer/)
  assert.match(securityPolicyEnginePageSource, /生效范围配置/)
  assert.match(securityPolicyEnginePageSource, /规则编排/)
  assert.match(securityPolicyEnginePageSource, /可视化编辑器/)
  assert.match(securityPolicyEnginePageSource, /代码编辑器/)
  assert.match(securityPolicyEnginePageSource, /异常检测配置/)
  assert.match(securityPolicyEnginePageSource, /测试与验证/)
  assert.match(securityPolicyEnginePageSource, /执行监督配置/)
  assert.match(securityPolicyEnginePageSource, /发布校验/)
  assert.match(securityPolicyEnginePageSource, /保存并启用/)
  assert.doesNotMatch(securityPolicyEnginePageSource, /安全态势看板[\s\S]*数据接入管理[\s\S]*密态计算管理[\s\S]*日志链路审计/)
})

test('接入规则配置按 PRD 实现统一数据接入安全规则', () => {
  assert.match(securityAccessRuleConfigPageSource, /export function SecurityAccessRuleConfigPage\(\)/)
  assert.match(securityAccessRuleConfigPageSource, /buildAccessRules/)
  assert.match(securityAccessRuleConfigPageSource, /数据接入管理/)
  assert.match(securityAccessRuleConfigPageSource, /SourceSecondaryTabs/)
  assert.match(securityAccessRuleConfigPageSource, /aria-label="数据接入管理二级导航"/)
  assert.match(securityAccessRuleConfigPageSource, /数据源配置/)
  assert.match(securityAccessRuleConfigPageSource, /接入规则配置/)
  assert.match(securityAccessRuleConfigPageSource, /接入监控/)
  assert.match(securityAccessRuleConfigPageSource, /<SourceSecondaryTabs[\s\S]*actions=\{/)
  assert.match(securityAccessRuleConfigPageSource, /配置数据源规则/)
  assert.match(securityAccessRuleConfigPageSource, /useSecurityDataSources/)
  assert.match(securityAccessRuleConfigPageSource, /source\.securityConfig/)
  assert.match(securityAccessRuleConfigPageSource, /source\.monitor\.checksumPassRate/)
  assert.doesNotMatch(securityAccessRuleConfigPageSource, /joinSecurityGovernanceItems/)
  assert.doesNotMatch(securityAccessRuleConfigPageSource, /导入规则模板/)
  assert.doesNotMatch(securityAccessRuleConfigPageSource, /导出规则清单/)
  assert.match(securityAccessRuleConfigPageSource, /接入网关/)
  assert.match(securityAccessRuleConfigPageSource, /完整性校验/)
  assert.match(securityAccessRuleConfigPageSource, /加密传输/)
  assert.match(securityAccessRuleConfigPageSource, /自动标签/)
  assert.match(securityAccessRuleConfigPageSource, /SM3/)
  assert.match(securityAccessRuleConfigPageSource, /SM4/)
  assert.match(securityAccessRuleConfigPageSource, /规则条件/)
  assert.match(securityAccessRuleConfigPageSource, /执行动作/)
  assert.doesNotMatch(securityAccessRuleConfigPageSource, /保存规则/)
  assert.doesNotMatch(securityAccessRuleConfigPageSource, /下发网关/)
  assert.doesNotMatch(securityAccessRuleConfigPageSource, /安全态势看板[\s\S]*访问控制管理[\s\S]*密态计算管理[\s\S]*日志链路审计/)
})

test('接入监控按 PRD 实现实时接入量、校验通过率和异常处置', () => {
  assert.match(securityAccessMonitoringPageSource, /export function SecurityAccessMonitoringPage\(\)/)
  assert.match(securityAccessMonitoringPageSource, /buildAccessMonitors/)
  assert.match(securityAccessMonitoringPageSource, /数据接入管理/)
  assert.match(securityAccessMonitoringPageSource, /SourceSecondaryTabs/)
  assert.match(securityAccessMonitoringPageSource, /aria-label="数据接入管理二级导航"/)
  assert.match(securityAccessMonitoringPageSource, /数据源配置/)
  assert.match(securityAccessMonitoringPageSource, /接入规则配置/)
  assert.match(securityAccessMonitoringPageSource, /接入监控/)
  assert.match(securityAccessMonitoringPageSource, /<SourceSecondaryTabs[\s\S]*actions=\{/)
  assert.doesNotMatch(securityAccessMonitoringPageSource, /导出监控快照/)
  assert.match(securityAccessMonitoringPageSource, /实时接入量/)
  assert.match(securityAccessMonitoringPageSource, /校验通过率/)
  assert.match(securityAccessMonitoringPageSource, /加密传输覆盖/)
  assert.match(securityAccessMonitoringPageSource, /异常网关/)
  assert.match(securityAccessMonitoringPageSource, /接入吞吐趋势/)
  assert.match(securityAccessMonitoringPageSource, /监控阈值/)
  assert.match(securityAccessMonitoringPageSource, /完整性校验/)
  assert.match(securityAccessMonitoringPageSource, /自动标签/)
  assert.match(securityAccessMonitoringPageSource, /日志链路审计/)
  assert.doesNotMatch(securityAccessMonitoringPageSource, /安全态势看板[\s\S]*访问控制管理[\s\S]*密态计算管理[\s\S]*日志链路审计/)
})

test('审计日志查询实现 log_query_screen_plan 的核心区块', () => {
  assert.match(securityLogQueryPageSource, /export function SecurityLogQueryPage\(\)/)
  assert.match(securityLogQueryPageSource, /buildAuditLogs/)
  assert.match(securityLogQueryPageSource, /policyDetailJson\.accessEvents/)
  assert.doesNotMatch(securityLogQueryPageSource, /createAuditLog/)
  assert.doesNotMatch(securityLogQueryPageSource, /joinSecurityGovernanceItems/)
  assert.match(securityLogQueryPageSource, /AccessControlSecondaryTabs/)
  assert.match(accessControlTabsSource, /日志链路审计/)
  assert.doesNotMatch(securityLogQueryPageSource, /操作链路追溯/)
  assert.doesNotMatch(securityLogQueryPageSource, /审计报告生成/)
  assert.doesNotMatch(securityLogQueryPageSource, /导出当前查询结果/)
  assert.doesNotMatch(securityLogQueryPageSource, /导出此日志/)
  assert.doesNotMatch(securityLogQueryPageSource, /批量导出/)
  assert.match(securityLogQueryPageSource, /高级搜索/)
  assert.doesNotMatch(securityLogQueryPageSource, /保存查询条件/)
  assert.match(securityLogQueryPageSource, /标记为证据/)
  assert.match(securityLogQueryPageSource, /最近1小时/)
  assert.match(securityLogQueryPageSource, /数据访问/)
  assert.match(securityLogQueryPageSource, /策略变更/)
  assert.match(securityLogQueryPageSource, /同态加密/)
  assert.match(securityLogQueryPageSource, /异常操作/)
  assert.match(securityLogQueryPageSource, /高风险/)
  assert.match(securityLogQueryPageSource, /AdvancedFilterPanel/)
  assert.match(securityLogQueryPageSource, /用户筛选/)
  assert.match(securityLogQueryPageSource, /操作对象/)
  assert.match(securityLogQueryPageSource, /结果与 IP/)
  assert.match(securityLogQueryPageSource, /本次查询总记录数/)
  assert.match(securityLogQueryPageSource, /风险操作数量/)
  assert.match(securityLogQueryPageSource, /操作类型分布/)
  assert.match(securityLogQueryPageSource, /操作高峰时段/)
  assert.match(securityLogQueryPageSource, /操作时间/)
  assert.match(securityLogQueryPageSource, /操作人/)
  assert.match(securityLogQueryPageSource, /操作详情/)
  assert.match(securityLogQueryPageSource, /LogDetailDrawer/)
  assert.match(securityLogQueryPageSource, /安全决策信息/)
  assert.match(securityLogQueryPageSource, /审计备注/)
  assert.doesNotMatch(securityLogQueryPageSource, /安全态势看板[\s\S]*数据接入管理[\s\S]*访问控制管理[\s\S]*密态计算管理/)
})

test('数据同态加密实现任务管理、加密参数、执行监控和结果归档', () => {
  assert.match(securityConfidentialComputingPageSource, /export function SecurityConfidentialComputingPage\(\)/)
  assert.match(securityConfidentialComputingPageSource, /buildTasks/)
  assert.doesNotMatch(securityConfidentialComputingPageSource, /AccessControlSecondaryTabs/)
  assert.match(securityConfidentialComputingPageSource, /HomomorphicSecondaryTabs/)
  assert.match(homomorphicTabsSource, /aria-label="数据同态加密二级导航"/)
  assert.match(homomorphicTabsSource, /同态加密任务/)
  assert.match(homomorphicTabsSource, /同态加密日志/)
  assert.match(homomorphicTabsSource, /\/security-governance\/homomorphic-encryption\/logs/)
  assert.doesNotMatch(homomorphicTabsSource, /同态加密引擎/)
  assert.doesNotMatch(homomorphicTabsSource, /\/security-governance\/homomorphic-encryption\/engine/)
  assert.match(homomorphicTabsSource, /数据同态加密二级导航/)
  assert.match(securityConfidentialComputingPageSource, /新建同态任务/)
  assert.match(securityConfidentialComputingPageSource, /加密引擎配置/)
  assert.match(securityConfidentialComputingPageSource, /EngineConnectionDrawer/)
  assert.match(securityConfidentialComputingPageSource, /同态加密引擎连接信息/)
  assert.match(securityConfidentialComputingPageSource, /服务地址/)
  assert.match(securityConfidentialComputingPageSource, /认证方式/)
  assert.match(securityConfidentialComputingPageSource, /测试连接/)
  assert.match(securityConfidentialComputingPageSource, /保存配置/)
  assert.match(securityConfidentialComputingPageSource, /同步执行状态/)
  assert.doesNotMatch(securityConfidentialComputingPageSource, /导出任务台账/)
  assert.match(securityConfidentialComputingPageSource, /运行中任务/)
  assert.match(securityConfidentialComputingPageSource, /待审批任务/)
  assert.match(securityConfidentialComputingPageSource, /整数精确型/)
  assert.match(securityConfidentialComputingPageSource, /浮点近似型/)
  assert.doesNotMatch(securityConfidentialComputingPageSource, /密钥会话/)
  assert.doesNotMatch(securityConfidentialComputingPageSource, /Paillier/)
  assert.match(securityConfidentialComputingPageSource, /密文计算执行/)
  assert.match(securityConfidentialComputingPageSource, /结果密文回传/)
  assert.match(securityConfidentialComputingPageSource, /真实执行日志/)
  assert.match(securityConfidentialComputingPageSource, /task\.status === 'pending_approval'/)
  assert.match(securityConfidentialComputingPageSource, /尚未审批，不会调用同态加密引擎/)
})

test('同态加密日志实现密态计算过程审计', () => {
  assert.match(securityHomomorphicLogsPageSource, /export function SecurityHomomorphicLogsPage\(\)/)
  assert.match(securityHomomorphicLogsPageSource, /buildHomomorphicLogs/)
  assert.match(securityHomomorphicLogsPageSource, /useConfidentialTasks/)
  assert.doesNotMatch(securityHomomorphicLogsPageSource, /joinSecurityGovernanceItems/)
  assert.match(securityHomomorphicLogsPageSource, /HomomorphicSecondaryTabs/)
  assert.match(homomorphicTabsSource, /同态加密日志/)
  assert.match(securityHomomorphicLogsPageSource, /同步日志/)
  assert.match(securityHomomorphicLogsPageSource, /参数下发/)
  assert.match(securityHomomorphicLogsPageSource, /密文计算/)
  assert.match(securityHomomorphicLogsPageSource, /结果密文回传/)
  assert.match(securityHomomorphicLogsPageSource, /整数精确型/)
  assert.match(securityHomomorphicLogsPageSource, /浮点近似型/)
  assert.doesNotMatch(securityHomomorphicLogsPageSource, /归档审计/)
  assert.doesNotMatch(securityHomomorphicLogsPageSource, /AccessControlSecondaryTabs/)
})

test('报告生成、配置版本和系统参数退出最小产品边界', () => {
  assert.doesNotMatch(securityGovernanceRoutesSource, /SecurityAuditReportPage/)
  assert.doesNotMatch(securityGovernanceRoutesSource, /SecurityVersionManagementPage/)
  assert.doesNotMatch(securityGovernanceRoutesSource, /SecurityFeaturePlaceholderPage/)
  assert.match(securityGovernanceRoutesSource, /\/security-governance\/audit\/report" element={<Navigate to="\/security-governance\/audit\/log-query"/)
  assert.match(securityGovernanceRoutesSource, /\/security-governance\/config\/version" element={<Navigate to="\/security-governance\/dashboard"/)
  assert.match(securityGovernanceRoutesSource, /\/security-governance\/config\/system-params" element={<Navigate to="\/security-governance\/dashboard"/)
})

test('数据标签管理实现 data_labels_screen_plan 的核心区块', () => {
  assert.match(securityDataLabelsPageSource, /export function SecurityDataLabelsPage\(\)/)
  assert.match(securityDataLabelsPageSource, /buildDataLabels/)
  assert.match(securityDataLabelsPageSource, /joinSecurityGovernanceItems/)
  assert.match(securityDataLabelsPageSource, /标签分类导航/)
  assert.match(securityDataLabelsPageSource, /数据敏感度分类/)
  assert.match(securityDataLabelsPageSource, /数据类型分类/)
  assert.match(securityDataLabelsPageSource, /业务域分类/)
  assert.match(securityDataLabelsPageSource, /自定义分类/)
  assert.match(securityDataLabelsPageSource, /数据标签管理/)
  assert.match(securityDataLabelsPageSource, /新建标签/)
  assert.doesNotMatch(securityDataLabelsPageSource, /批量导入/)
  assert.doesNotMatch(securityDataLabelsPageSource, /<Download className="h-4 w-4" \/>\s*导出/)
  assert.doesNotMatch(securityDataLabelsPageSource, /标签分类管理/)
  assert.match(securityDataLabelsPageSource, /标签总数/)
  assert.match(securityDataLabelsPageSource, /已使用标签/)
  assert.match(securityDataLabelsPageSource, /待确认标签/)
  assert.match(securityDataLabelsPageSource, /敏感标签数/)
  assert.match(securityDataLabelsPageSource, /搜索标签名称、描述、关键词/)
  assert.match(securityDataLabelsPageSource, /按使用次数/)
  assert.match(securityDataLabelsPageSource, /关联数据源/)
  assert.match(securityDataLabelsPageSource, /关联策略/)
  assert.match(securityDataLabelsPageSource, /LabelDrawer/)
  assert.match(securityDataLabelsPageSource, /访问控制规则/)
  assert.match(securityDataLabelsPageSource, /使用情况分析/)
  assert.match(securityDataLabelsPageSource, /变更历史时间线/)
  assert.match(securityDataLabelsPageSource, /h-dvh max-h-dvh/)
  assert.match(securityDataLabelsPageSource, /min-h-0 flex-1 space-y-5 overflow-y-auto/)
  assert.doesNotMatch(securityDataLabelsPageSource, /安全态势看板[\s\S]*数据接入管理[\s\S]*访问控制管理[\s\S]*密态计算管理[\s\S]*日志链路审计/)
})

test('数据安全管控页面沿用轻量目录数据模式', () => {
  assert.match(
    portalContextSource,
    /appPathname === '\/security-governance'[\s\S]*appPathname === '\/security-governance\/dashboard'[\s\S]*appPathname === '\/security-governance\/resources'[\s\S]*\? 'list'[\s\S]*: 'full'/,
  )
})

test('安全态势看板实现 dashboard_screen_plan 的核心区块', () => {
  assert.match(securityDashboardPageSource, /export function SecurityDashboardPage\(\)/)
  assert.doesNotMatch(securityDashboardPageSource, /实时监控数据接入、动态访问控制、跨域密态计算和审计告警状态/)
  assert.doesNotMatch(securityDashboardPageSource, /timeRanges/)
  assert.doesNotMatch(securityDashboardPageSource, /TimeRange/)
  assert.doesNotMatch(securityDashboardPageSource, /label: '最近1小时'/)
  assert.doesNotMatch(securityDashboardPageSource, /label: '24小时'/)
  assert.doesNotMatch(securityDashboardPageSource, /label: '7天'/)
  assert.doesNotMatch(securityDashboardPageSource, /label: '30天'/)
  assert.doesNotMatch(securityDashboardPageSource, /RefreshCw/)
  assert.doesNotMatch(securityDashboardPageSource, /Download/)
  assert.doesNotMatch(securityDashboardPageSource, /刷新/)
  assert.doesNotMatch(securityDashboardPageSource, /导出报告/)
  assert.doesNotMatch(securityDashboardPageSource, /跨域密态计算/)
  assert.doesNotMatch(securityDashboardPageSource, /策略命中率/)
  assert.doesNotMatch(securityDashboardPageSource, /审计报告周期/)
  assert.doesNotMatch(securityDashboardPageSource, /dashboardSecondaryNavItems/)
  assert.doesNotMatch(securityDashboardPageSource, /二级导航/)
  assert.doesNotMatch(securityDashboardPageSource, /xl:grid-cols-\[248px_minmax\(0,1fr\)\]/)
  assert.match(securityDashboardPageSource, /整体综合情况/)
  assert.match(securityDashboardPageSource, /实时运行情况/)
  assert.match(securityDashboardPageSource, /moduleSummaries/)
  assert.match(securityDashboardPageSource, /realtimeItems/)
  assert.match(securityDashboardPageSource, /ModuleSummaryCard/)
  assert.match(securityDashboardPageSource, /RealtimeStatusCard/)
  assert.doesNotMatch(securityDashboardPageSource, /NBaaS|OpenFHE/)
  assert.match(securityDashboardPageSource, /聚合数据接入、资源管控、访问控制与同态加密的核心运行指标/)
  assert.match(securityDashboardPageSource, /分类分级/)
  assert.match(securityDashboardPageSource, /接入完整性/)
  assert.match(securityDashboardPageSource, /homomorphicCompletedCount/)
  assert.match(securityDashboardPageSource, /今日数据接入量/)
  assert.match(securityDashboardPageSource, /访问请求总数/)
  assert.match(securityDashboardPageSource, /活跃安全策略数/)
  assert.match(securityDashboardPageSource, /安全告警数/)
  assert.match(securityDashboardPageSource, /实时安全事件流/)
  assert.match(securityDashboardPageSource, /数据源接入状态/)
  assert.match(securityDashboardPageSource, /访问异常分析/)
  assert.match(securityDashboardPageSource, /策略引擎性能监控/)
  assert.match(securityDashboardPageSource, /策略启用率/)
  assert.match(securityDashboardPageSource, /脱敏覆盖率/)
  assert.match(securityDashboardPageSource, /规则执行平均耗时/)
  assert.match(securityDashboardPageSource, /当前队列任务数/)
  assert.match(securityDashboardPageSource, /最近24小时性能趋势/)
})

test('同态加密运行时、代理和演示数据只保留两类密态算法', () => {
  assert.match(securityRuntimeSource, /const DATA_SOURCE_COLLECTION = 'security_data_sources'/)
  assert.match(securityRuntimeSource, /const CONFIDENTIAL_TASK_COLLECTION = 'security_confidential_tasks'/)
  assert.match(securityRuntimeSource, /export type OpenFheAlgorithm = 'BFV' \| 'CKKS'/)
  assert.match(securityRuntimeSource, /supportedAlgorithms: \['BFV', 'CKKS'\]/)
  assert.match(viteConfigSource, /'\/homomorphic-engine-api'/)
  assert.match(viteConfigSource, /'\*\*\/docker\/storage\/\*\*'/)
  assert.match(seedDemoSource, /pruneDictionaryItems\('compute_algorithm', \['bfv', 'ckks'\]\)/)
  assert.match(seedDemoSource, /HE-INT-DEMO-001/)
  assert.match(seedDemoSource, /HE-FLOAT-DEMO-001/)
  assert.doesNotMatch(seedDemoSource, /HE-BFV-DEMO-001|HE-CKKS-DEMO-001/)
  assert.match(seedDemoSource, /compute_request: \{ operation: 'sum', values:/)
  assert.match(seedDemoSource, /compute_request: \{ operation: 'mean', values:/)
  assert.match(securityRuntimeSource, /computeRequest: OpenFheComputeRequest/)
  assert.match(securityRuntimeSource, /task\.computeRequest\.operation/)
  assert.match(securityRuntimeSource, /task\.computeRequest\.values/)
  assert.match(openFheMainSource, /@app\.get\("\/health"\)/)
  assert.match(openFheMainSource, /@app\.post\("\/v1\/tasks\/execute"\)/)
  assert.match(openFheCryptoSource, /CCParamsBFVRNS/)
  assert.match(openFheCryptoSource, /CCParamsCKKSRNS/)
  assert.match(openFheCryptoSource, /context\.EvalAdd/)
  assert.match(dockerComposeSource, /platform: linux\/amd64/)
  assert.doesNotMatch(seedDemoSource, /secure_mpc_aggregation|federated_learning/)
  assert.doesNotMatch(openFheMainSource, /Paillier|MPC|federated/i)
})

test('安全档案优先关联独立字段安全集合并保留旧 JSON 回退', () => {
  assert.match(securityGovernanceDataSource, /const SECURITY_FIELD_COLLECTION = 'eco_resource_security_fields'/)
  assert.match(securityGovernanceDataSource, /fieldsByPolicy/)
  assert.match(securityGovernanceDataSource, /normalizedPersistedFieldRows\.length > 0/)
  assert.match(securityGovernanceDataSource, /row\.field_tags/)
  assert.match(securityGovernanceDataSource, /fieldProfilesJson/)
  assert.match(securityGovernanceDataSource, /fieldPoliciesJson/)
})

test('数据资源管控页面按四类数据类型提供二级菜单和四种分类树', () => {
  assert.match(securityPageSource, /export function SecurityGovernancePage\(\)/)
  assert.match(securityPageSource, /type ResourceControlTypeId = 'database-table' \| 'data-api' \| 'spatial-data' \| 'document-data'/)
  assert.match(securityPageSource, /RESOURCE_CONTROL_TABS/)
  assert.match(securityPageSource, /label: '数据库表'/)
  assert.match(securityPageSource, /label: '数据API'/)
  assert.match(securityPageSource, /label: '空间数据'/)
  assert.match(securityPageSource, /label: '文档数据'/)
  assert.match(securityPageSource, /function resolveResourceControlType\(item: SecurityGovernanceJoinedItem\)/)
  assert.match(securityPageSource, /getCatalogResourceTypeFilterId\(item\)/)
  assert.match(securityPageSource, /nextSearchParams\.set\('type', typeId\)/)
  assert.match(securityPageSource, /\/security-governance\/resources\?\$\{nextSearchParams\.toString\(\)\}/)
  assert.match(securityPageSource, /inline-flex flex-wrap gap-2 rounded-\[18px\] border border-\[rgba\(var\(--theme-soft-rgb\),0\.18\)\] bg-\[color-mix\(in_srgb,var\(--surface-glass\)_92%,transparent\)\] p-2 shadow-\[inset_0_1px_0_rgba\(255,255,255,0\.08\)\] backdrop-blur/)
  assert.match(securityPageSource, /inline-flex min-w-\[9rem\] items-center gap-2 rounded-\[14px\] px-4 py-3 text-\[0\.875rem\] font-medium transition/)
  assert.match(securityPageSource, /hover:bg-\[var\(--surface-raised\)\] hover:text-\[var\(--primary\)\]/)
  assert.match(securityPageSource, /useSecurityGovernancePolicies\(true\)/)
  assert.match(securityPageSource, /buildSecurityGovernanceSnapshot/)
  assert.match(securityPageSource, /ResourceEditDialog/)
  assert.match(securityPageSource, /canManageCatalogResources\(session\?\.user\.roles\)/)
  assert.match(securityPageSource, /resolveCreateResourceTypeOptionId\(activeResourceType, editOptions\.serviceTypeOptions\)/)
  assert.match(securityPageSource, /<Plus className="h-4 w-4" \/>\s*新建数据资源/)
  assert.match(securityPageSource, /mode="create"/)
  assert.match(securityPageSource, /variant="drawer"/)
  assert.match(securityPageSource, /initialValues=\{createResourceInitialValues\}/)
  assert.match(securityPageSource, /await refresh\(\)/)
  assert.match(securityPageSource, /title="数据分类"/)
  assert.match(securityPageSource, /title="业务分类"/)
  assert.match(securityPageSource, /title="安全分类"/)
  assert.match(securityPageSource, /title="安全等级"/)
  assert.match(securityPageSource, /categoryTree/)
  assert.match(securityPageSource, /businessAttributeTree/)
  assert.match(securityPageSource, /informationCategoryTree/)
  assert.match(securityPageSource, /joinSecurityGovernanceItems/)
  assert.match(securityPageSource, /businessAttributeNodeId/)
  assert.match(securityPageSource, /businessCategoryNode/)
  assert.match(securityPageSource, /securityCategory/)
  assert.match(securityPageSource, /securityLevel/)
  assert.match(securityPageSource, /to=\{withEmbed\(`\/security-governance\/\$\{item\.policyId\}`\)\}/)
  assert.match(securityPageSource, /className="block text-\[1rem\] font-semibold leading-7 text-\[var\(--text-main\)\] transition hover:text-\[var\(--primary\)\]"/)
  assert.match(securityPageSource, /字段监督摘要/)
  assert.match(securityPageSource, /数据主体类型：/)
  assert.match(securityPageSource, /责任部门：/)
  assert.match(securityPageSource, /要求访问范围：/)
  assert.match(securityPageSource, /要求共享范围：/)
  assert.match(securityPageSource, /要求脱敏方式：/)
  assert.match(securityPageSource, /按资源名称、数据分类、业务分类、安全分类、安全等级或风险关键词检索/)
  assert.doesNotMatch(securityPageSource, /SecurityGovernanceTabId/)
  assert.doesNotMatch(securityPageSource, /SECURITY_GOVERNANCE_TABS/)
  assert.doesNotMatch(securityPageSource, /activeTab !== 'classification'/)
  assert.doesNotMatch(securityPageSource, /生态环境信息分类/)
  assert.doesNotMatch(securityPageSource, /分类分级总览与安全策略检索/)
  assert.doesNotMatch(securityPageSource, /仅基于当前目录已有真实字段构建安全视角/)
  assert.doesNotMatch(securityPageSource, /当前筛选摘要/)
  assert.doesNotMatch(securityPageSource, /共筛选出 .* 条资源，当前展示第/)
  assert.doesNotMatch(securityPageSource, /查看安全详情/)
  assert.doesNotMatch(securityPageSource, /数据资源分类分布/)
  assert.doesNotMatch(securityPageSource, /信息分类分布/)
  assert.doesNotMatch(securityPageSource, /安全策略分布/)
})

test('数据安全管控详情页提供独立安全视角展示', () => {
  assert.match(securityDetailPageSource, /export function SecurityGovernanceDetailPage\(\)/)
  assert.match(securityDetailPageSource, /useLatestResourceBatchStat/)
  assert.match(securityDetailPageSource, /LatestDataPreviewPanel/)
  assert.match(securityDetailPageSource, /安全管控信息/)
  assert.match(securityDetailPageSource, /安全状态/)
  assert.match(securityDetailPageSource, /数据接入管理一致口径/)
  assert.match(securityDetailPageSource, /访问控制管理一致口径/)
  assert.match(securityDetailPageSource, /日志链路审计一致口径/)
  assert.match(securityDetailPageSource, /物理表参考与业务时间字段/)
  assert.match(securityDetailPageSource, /最新数据预览/)
  assert.match(securityDetailPageSource, /返回安全管控/)
  assert.match(securityDetailPageSource, /资源目录详情/)
})
