import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const detailPageSource = readFileSync(resolve(process.cwd(), 'src/pages/security-governance-detail-page.tsx'), 'utf8')
const resourceFieldsPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-fields-panel.tsx'), 'utf8')
const resourceApisPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-apis-panel.tsx'), 'utf8')
const accessPoliciesPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-access-policies-panel.tsx'), 'utf8')
const homomorphicPanelSource = readFileSync(resolve(process.cwd(), 'src/components/resource-homomorphic-panel.tsx'), 'utf8')
const collectionPageSource = readFileSync(resolve(process.cwd(), 'src/components/security-v3-collection-page.tsx'), 'utf8')
const moduleTabsSource = readFileSync(resolve(process.cwd(), 'src/components/security-module-tabs.tsx'), 'utf8')
const relationSource = readFileSync(resolve(process.cwd(), 'src/lib/resource-security-relations.ts'), 'utf8')

test('安全管控详情页支持返回原列表并兜底跳回数据资源列表', () => {
  assert.match(detailPageSource, /type SecurityGovernanceDetailLocationState = \{/)
  assert.match(detailPageSource, /const returnTo = typeof locationState\?\.returnTo === 'string'/)
  assert.match(detailPageSource, /const handleGoBack = \(\) => \{/)
  assert.match(detailPageSource, /if \(returnTo\) \{/)
  assert.match(detailPageSource, /navigate\(returnTo\)/)
  assert.match(detailPageSource, /navigate\(-1\)/)
  assert.match(detailPageSource, /navigate\(withEmbed\('\/security-governance\/resources\/catalog'\)\)/)
  assert.match(detailPageSource, /返回数据资源/)
})

test('安全管控详情页按资源 ID 查询并保留跳转资源目录详情入口', () => {
  assert.match(detailPageSource, /catalogItems\.find\(\(entry\) => entry\.id === id\)/)
  assert.match(detailPageSource, /to=\{withEmbed\(`\/catalog\/\$\{item\.id\}`\)\}/)
  assert.match(detailPageSource, /资源目录详情/)
  assert.match(detailPageSource, /ResourceFieldsPanel/)
  assert.doesNotMatch(detailPageSource, /SecurityGovernanceProfileEditDialog/)
  assert.doesNotMatch(detailPageSource, /SecurityGovernanceFieldEditDialog/)
  assert.doesNotMatch(detailPageSource, /<ResourceEditDialog/)
  assert.doesNotMatch(detailPageSource, /<DataItemsEditDialog/)
})

test('详情页移除物理表和最新预览 tab', () => {
  assert.doesNotMatch(detailPageSource, /\['physicalTables', '物理表'\]/)
  assert.doesNotMatch(detailPageSource, /\['latestPreview', '最新预览'\]/)
  assert.doesNotMatch(detailPageSource, /activeTab === 'physicalTables'/)
  assert.doesNotMatch(detailPageSource, /activeTab === 'latestPreview'/)
  assert.doesNotMatch(detailPageSource, /<PhysicalTablesEditDialog/)
  assert.doesNotMatch(detailPageSource, /<LatestDataPreviewPanel/)
})

test('资源字段随当前数据资源维护且不再作为独立二级导航', () => {
  assert.match(resourceFieldsPanelSource, /collection: 'eco_resource_security_fields'/)
  assert.match(resourceFieldsPanelSource, /filter: \{ resource_id: resourceId \}/)
  assert.match(resourceFieldsPanelSource, /transformSaveValues: \(values\) => \(\{ \.\.\.values, resource_id: resourceId \}\)/)
  assert.match(resourceFieldsPanelSource, /<SecurityV3CollectionPage config=\{config\} embedded \/>/)
  assert.match(collectionPageSource, /Boolean\(value \?\? field\.defaultValue \?\? false\)/)
  assert.doesNotMatch(moduleTabsSource, /\/security-governance\/resources\/fields/)
})

test('安全管控详情页使用 tab 展示并将当前 tab 写入 URL', () => {
  assert.match(detailPageSource, /type SecurityGovernanceDetailTabKey = 'overview' \| 'resourceFields' \| 'apiInfo' \| 'accessPolicies' \| 'homomorphic' \| 'accessInfo' \| 'status' \| 'lineage'/)
  assert.match(detailPageSource, /const requestedTab = searchParams\.get\('tab'\) as SecurityGovernanceDetailTabKey \| null/)
  assert.match(detailPageSource, /const detailTabs: Array<\[SecurityGovernanceDetailTabKey, string\]> = \[/)
  assert.match(detailPageSource, /\['overview', '基本信息'\]/)
  assert.match(detailPageSource, /\['resourceFields', '资源字段'\]/)
  assert.match(detailPageSource, /\['apiInfo', 'API 信息'\]/)
  assert.match(detailPageSource, /\['accessPolicies', '访问策略'\]/)
  assert.match(detailPageSource, /\['homomorphic', '同态加密'\]/)
  assert.match(detailPageSource, /\['accessInfo', '安全接入'\]/)
  assert.match(detailPageSource, /\['lineage', '血缘关系'\]/)
  assert.match(detailPageSource, /\['status', '安全状态'\]/)
  assert.match(detailPageSource, /const handleTabChange = \(tabKey: SecurityGovernanceDetailTabKey\) => \{/)
  assert.match(detailPageSource, /pathname: location\.pathname/)
  assert.match(detailPageSource, /search: `\?\$\{buildTabSearchParams\(tabKey\)\.toString\(\)\}`/)
  assert.match(detailPageSource, /replace: true/)
  assert.match(detailPageSource, /state: locationState \?\? undefined/)
  assert.match(detailPageSource, /<ResourceFieldsPanel[\s\S]*resourceId=\{item\.id\}[\s\S]*homomorphicFieldCodes=\{securityRelations\.homomorphicFieldCodes\}/)
  assert.match(detailPageSource, /LineageRelationGraph/)
  assert.match(detailPageSource, /数据安全血缘关系/)
})

test('资源详情按真实关系聚合 API、数据源、接入安全和运行字段引用', () => {
  assert.match(relationSource, /listSecurityV3Records\('security_api_resources'/)
  assert.match(relationSource, /listSecurityV3Records\('security_data_sources'/)
  assert.match(relationSource, /listSecurityV3Records\('security_ingest_logs'/)
  assert.match(relationSource, /listSecurityV3Records\('security_policy_decision_logs'/)
  assert.match(relationSource, /listSecurityV3Records\('eco_resource_security_policies'/)
  assert.match(relationSource, /listSecurityV3Records\('security_confidential_tasks'/)
  assert.match(detailPageSource, /activeTab === 'apiInfo'/)
  assert.match(detailPageSource, /activeTab === 'accessInfo'/)
  assert.match(detailPageSource, /传输保护/)
  assert.match(detailPageSource, /完整性校验/)
  assert.match(detailPageSource, /最近接入校验/)
})

test('每个数据资源可在详情页维护并由 Python 运行服务发布 API', () => {
  assert.match(detailPageSource, /<ResourceApisPanel/)
  assert.match(resourceApisPanelSource, /collection: 'security_api_resources'/)
  assert.match(resourceApisPanelSource, /filter: \{ resource_id: resourceId \}/)
  assert.match(resourceApisPanelSource, /createLabel: '新增 API 信息'/)
  assert.match(resourceApisPanelSource, /defaultValue: '\/internal\/resource-query'/)
  assert.match(resourceApisPanelSource, /name: 'runtime_config_json'/)
  assert.match(resourceApisPanelSource, /publishSecurityApi/)
  assert.match(resourceApisPanelSource, /签名认证、访问策略、限流、风险判定与审计记录；没有已发布访问策略时默认拒绝调用/)
})

test('资源详情提供真实可执行的安全访问策略配置', () => {
  assert.match(detailPageSource, /<ResourceAccessPoliciesPanel/)
  assert.match(accessPoliciesPanelSource, /collection: 'eco_resource_security_policies'/)
  assert.match(accessPoliciesPanelSource, /policy_kind: 'access_policy'/)
  assert.match(accessPoliciesPanelSource, /name: 'subject_id'/)
  assert.match(accessPoliciesPanelSource, /name: 'api_resource_id'/)
  assert.doesNotMatch(accessPoliciesPanelSource, /name: 'field_allowlist_json'/)
  assert.match(accessPoliciesPanelSource, /name: 'abnormal_access_rules_json'/)
  assert.match(accessPoliciesPanelSource, /name: 'max_requests_per_minute'/)
  assert.match(accessPoliciesPanelSource, /name: 'risk_threshold'/)
  assert.match(accessPoliciesPanelSource, /publishSecurityPolicy/)
  assert.match(accessPoliciesPanelSource, /listSecurityV3Records\('security_policy_decision_logs'/)
  assert.match(accessPoliciesPanelSource, /访问策略最近执行日志/)
})

test('资源详情提供不保存私钥和明文值的同态任务配置', () => {
  assert.match(detailPageSource, /<ResourceHomomorphicPanel/)
  assert.match(homomorphicPanelSource, /collection: 'security_confidential_tasks'/)
  assert.match(homomorphicPanelSource, /name: 'subject_id'/)
  assert.match(homomorphicPanelSource, /name: 'api_resource_id'/)
  assert.match(homomorphicPanelSource, /name: 'measure_field_code'/)
  assert.match(homomorphicPanelSource, /name: 'crypto_key_id'/)
  assert.match(homomorphicPanelSource, /任务配置不保存私钥、Secret 或原始明文值/)
  assert.doesNotMatch(homomorphicPanelSource, /name: 'private_key'/)
  assert.doesNotMatch(homomorphicPanelSource, /name: 'values'/)
  assert.match(homomorphicPanelSource, /同态加密最近执行日志/)
  assert.match(homomorphicPanelSource, /summary\.events/)
  assert.match(homomorphicPanelSource, /summary\.logs/)
})

test('安全接入的数据源信息以单行全宽卡片横向铺开', () => {
  assert.match(detailPageSource, /title="安全接入"/)
  assert.match(detailPageSource, /securityRelations\.sources\.map[\s\S]*mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4/)
  assert.doesNotMatch(detailPageSource, /mt-5 grid gap-4 xl:grid-cols-2[\s\S]*securityRelations\.sources\.map/)
})

test('资源字段移除未进入策略与同态运行链路的展示型安全字段', () => {
  assert.doesNotMatch(resourceFieldsPanelSource, /label: '策略引擎'/)
  assert.match(resourceFieldsPanelSource, /label: '同态计算'/)
  assert.doesNotMatch(resourceFieldsPanelSource, /label: '直接标识符'/)
  assert.doesNotMatch(resourceFieldsPanelSource, /label: '准标识符'/)
  assert.doesNotMatch(resourceFieldsPanelSource, /label: '重要字段'/)
  assert.doesNotMatch(resourceFieldsPanelSource, /label: '信息分类'/)
  assert.doesNotMatch(resourceFieldsPanelSource, /label: '敏感类型'/)
})

test('安全管控详情页与数据接入和日志审计模块口径保持一致', () => {
  assert.match(detailPageSource, /function ModuleAlignmentStrip/)
  assert.match(detailPageSource, /数据接入管理一致口径/)
  assert.match(detailPageSource, /数据源配置/)
  assert.match(detailPageSource, /接入规则配置/)
  assert.match(detailPageSource, /接入日志/)
  assert.match(detailPageSource, /\/security-governance\/ingest\/sources/)
  assert.match(detailPageSource, /\/security-governance\/ingest\/validation-rules/)
  assert.match(detailPageSource, /\/security-governance\/ingest\/logs/)
  assert.doesNotMatch(detailPageSource, /访问控制管理一致口径/)
  assert.doesNotMatch(detailPageSource, /数据同态加密一致口径/)
  assert.match(detailPageSource, /日志链路审计一致口径/)
  assert.match(detailPageSource, /调用与决策日志/)
  assert.match(detailPageSource, /\/security-governance\/access\/audit/)
  assert.doesNotMatch(detailPageSource, /操作链路追溯/)
  assert.doesNotMatch(detailPageSource, /审计报告生成/)
  assert.doesNotMatch(detailPageSource, /\/security-governance\/audit\/trace/)
  assert.doesNotMatch(detailPageSource, /\/security-governance\/audit\/report/)
})

test('基本信息只保留资源基础信息并使用真实运行指标', () => {
  assert.match(detailPageSource, /资源编码/)
  assert.match(detailPageSource, /资源状态/)
  assert.match(detailPageSource, /数据分类/)
  assert.match(detailPageSource, /业务分类/)
  assert.match(detailPageSource, /来源单位/)
  assert.match(detailPageSource, /来源系统/)
  assert.match(detailPageSource, /更新周期/)
  assert.match(detailPageSource, /title: '字段数量'/)
  assert.match(detailPageSource, /latestStatRecord\?\.metainfo\.field_count \?\? item\.fieldCount/)
  assert.match(detailPageSource, /title: 'API 访问次数'/)
  assert.match(detailPageSource, /securityRelations\.decisionLogs\.length/)
  assert.match(detailPageSource, /title: '访问策略数量'/)
  assert.match(detailPageSource, /title: '接入抽样数量'/)
  assert.match(detailPageSource, /latestStatRecord\.metainfo\.record_count/)
  assert.doesNotMatch(detailPageSource, /<TopicPill>资源编码：/)
  assert.doesNotMatch(detailPageSource, /<TopicPill>来源单位：/)
  assert.doesNotMatch(detailPageSource, /<TopicPill>来源系统：/)
  assert.doesNotMatch(detailPageSource, /<TopicPill>资源状态：/)
  assert.doesNotMatch(detailPageSource, /安全档案编号/)
  assert.doesNotMatch(detailPageSource, /安全分类：/)
  assert.doesNotMatch(detailPageSource, /安全等级：/)
  assert.doesNotMatch(detailPageSource, /管控标识/)
  assert.doesNotMatch(detailPageSource, /安全责任人/)
  assert.doesNotMatch(detailPageSource, /共享范围/)
  assert.doesNotMatch(detailPageSource, /审批模式/)
  assert.doesNotMatch(detailPageSource, /导出范围/)
  assert.doesNotMatch(detailPageSource, /复核计划/)
  assert.doesNotMatch(detailPageSource, /定级依据/)
})
