import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const diagramSource = readFileSync(resolve(process.cwd(), 'src/components/home-architecture-diagram.tsx'), 'utf8')
const homePageSource = readFileSync(resolve(process.cwd(), 'src/pages/home-page.tsx'), 'utf8')
const indexCssSource = readFileSync(resolve(process.cwd(), 'src/index.css'), 'utf8')

test('首页接入总体架构示意图组件', () => {
  assert.match(homePageSource, /import \{ HomeArchitectureDiagram \} from '\.\.\/components\/home-architecture-diagram'/)
  assert.match(homePageSource, /<HomeArchitectureDiagram \/>/)
})

test('总体架构示意图包含五列主体、上下贯通带和底部统一运行统计', () => {
  assert.match(diagramSource, /const DIAGRAM_HEIGHT = 760/)
  assert.match(diagramSource, /const DIAGRAM_WIDTH = 1448/)
  assert.match(diagramSource, /width: 1208,/)
  assert.match(diagramSource, /lines: \['数据统一接入'\]/)
  assert.match(diagramSource, /lines: \['数据资源管控'\]/)
  assert.match(diagramSource, /lines: \['数据安全管控'\]/)
  assert.match(diagramSource, /lines: \['数据应用管控'\]/)
  assert.match(diagramSource, /lines: \['数据共享管控'\]/)
  assert.match(diagramSource, /lines: \['数据仓库'\]/)
  assert.match(diagramSource, /lines: \['数据中台'\]/)
  assert.match(diagramSource, /lines: \['应用系统'\]/)
  assert.match(diagramSource, /lines: \['数据统一接入'\],\s*\n\s*}\s*,\s*\n\s*{\s*\n\s*id: 'governance-catalog'/)
  assert.match(diagramSource, /lines: \['数据资源目录'\]/)
  assert.match(diagramSource, /lines: \['数据API'\]/)
  assert.match(diagramSource, /lines: \['分类分级'\]/)
  assert.match(diagramSource, /lines: \['访问策略'\]/)
  assert.match(diagramSource, /lines: \['共享策略'\]/)
  assert.match(diagramSource, /lines: \['应用管理'\]/)
  assert.match(diagramSource, /lines: \['应用需求'\]/)
  assert.match(diagramSource, /lines: \['外部需求'\]/)
  assert.match(diagramSource, /lines: \['同域访问'\]/)
  assert.match(diagramSource, /lines: \['跨域访问'\]/)
  assert.match(diagramSource, /lines: \['同态加密'\]/)
  assert.match(diagramSource, /node\.lines\.slice\(0, 3\)/)
  assert.match(diagramSource, /node\.lines\.slice\(3\)/)
  assert.match(diagramSource, />\s*供给\s*</)
  assert.match(diagramSource, />\s*需求\s*</)
  assert.match(diagramSource, /数据来源一本账/)
  assert.match(diagramSource, /数据资源一本账/)
  assert.match(diagramSource, /安全策略一本账/)
  assert.match(diagramSource, /应用访问一本账/)
  assert.match(diagramSource, /数据需求一本账/)
  assert.match(diagramSource, /数据共享一本账/)
  assert.match(diagramSource, /lines: \['数据管控统一运行统计分析'\]/)
  assert.doesNotMatch(diagramSource, /横向贯通/)
})

test('总体架构示意图采用 SVG 动态流光连线', () => {
  assert.match(diagramSource, /<animate attributeName="stroke-dashoffset"/)
  assert.match(diagramSource, /<animateMotion/)
  assert.match(diagramSource, /stroke=\{`url\(#\$\{prefix\}-flow\)`\}/)
  assert.match(diagramSource, /buildHorizontalEdgePath\(/)
  assert.match(diagramSource, /buildVerticalEdgePath\(/)
  assert.match(diagramSource, /\{ from: 'ledger-unified', to: 'col-source', straight: true \}/)
  assert.match(diagramSource, /\{ from: 'ledger-unified', to: 'col-governance', straight: true \}/)
  assert.match(diagramSource, /\{ from: 'ledger-unified', to: 'col-security', straight: true \}/)
  assert.match(diagramSource, /\{ from: 'ledger-unified', to: 'col-application', straight: true \}/)
  assert.match(diagramSource, /\{ from: 'ledger-unified', to: 'col-sharing', straight: true \}/)
  assert.match(diagramSource, /\{ from: 'governance-catalog', to: 'governance-api' \}/)
  assert.match(diagramSource, /\{ from: 'governance-catalog', to: 'security-classification' \}/)
  assert.match(diagramSource, /\{ from: 'governance-api', to: 'security-access', emphasize: true \}/)
  assert.match(diagramSource, /\{ from: 'application-manage', to: 'sharing-same-domain', emphasize: true \}/)
  assert.match(diagramSource, /\{ from: 'application-demand', to: 'sharing-cross-domain', emphasize: true \}/)
  assert.match(diagramSource, /\{ from: 'application-external-demand', to: 'sharing-homomorphic-encryption', emphasize: true \}/)
  assert.doesNotMatch(diagramSource, /\{ from: 'governance-source', to: 'security-classification' \}/)
  assert.doesNotMatch(diagramSource, /\{ from: 'governance-api', to: 'application-demand' \}/)
  assert.doesNotMatch(diagramSource, /\{ from: 'governance-api', to: 'application-manage', emphasize: true \}/)
  assert.doesNotMatch(diagramSource, /\{ from: 'security-sharing', to: 'application-manage' \}/)
  assert.doesNotMatch(diagramSource, /col-warehouse/)
  assert.match(diagramSource, /straight: true/)
  assert.match(diagramSource, /const lineX = from\.kind === 'top' \? to\.x : from\.x/)
  assert.match(diagramSource, /return `M \$\{lineX\} \$\{startY\} L \$\{lineX\} \$\{endY\}`/)
})

test('总体架构示意图文字颜色跟随主题变量在亮暗模式切换', () => {
  assert.match(diagramSource, /color: 'var\(--lineage-node-title\)'/)
  assert.match(indexCssSource, /--lineage-node-title: #274460;/)
  assert.match(indexCssSource, /:root\[data-theme='dark'\][\s\S]*--lineage-node-title: #e4effd;/)
})
